/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssetPriceHistoryInput model module.
 * @module model/AssetPriceHistoryInput
 * @version 1.25.0
 */
class AssetPriceHistoryInput {
    /**
     * Constructs a new <code>AssetPriceHistoryInput</code>.
     * Input schema for creating AssetPriceHistory
     * @alias module:model/AssetPriceHistoryInput
     */
    constructor() { 
        
        AssetPriceHistoryInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetPriceHistoryInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetPriceHistoryInput} obj Optional instance to populate.
     * @return {module:model/AssetPriceHistoryInput} The populated <code>AssetPriceHistoryInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetPriceHistoryInput();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
            if (data.hasOwnProperty('endpoint_id')) {
                obj['endpoint_id'] = ApiClient.convertToType(data['endpoint_id'], 'String');
            }
            if (data.hasOwnProperty('price_usd')) {
                obj['price_usd'] = ApiClient.convertToType(data['price_usd'], 'Number');
            }
            if (data.hasOwnProperty('date_ended')) {
                obj['date_ended'] = ApiClient.convertToType(data['date_ended'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetPriceHistoryInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetPriceHistoryInput</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['asset_id'] && !(typeof data['asset_id'] === 'string' || data['asset_id'] instanceof String)) {
            throw new Error("Expected the field `asset_id` to be a primitive type in the JSON string but got " + data['asset_id']);
        }
        // ensure the json data is a string
        if (data['endpoint_id'] && !(typeof data['endpoint_id'] === 'string' || data['endpoint_id'] instanceof String)) {
            throw new Error("Expected the field `endpoint_id` to be a primitive type in the JSON string but got " + data['endpoint_id']);
        }

        return true;
    }


}



/**
 * FK to assets. NULL when this record belongs to an endpoint.
 * @member {String} asset_id
 */
AssetPriceHistoryInput.prototype['asset_id'] = undefined;

/**
 * FK to endpoints. NULL when this record belongs to an asset.
 * @member {String} endpoint_id
 */
AssetPriceHistoryInput.prototype['endpoint_id'] = undefined;

/**
 * Optional.
 * @member {Number} price_usd
 */
AssetPriceHistoryInput.prototype['price_usd'] = undefined;

/**
 * SCD Type 2 — when this price record was superseded
 * @member {Date} date_ended
 */
AssetPriceHistoryInput.prototype['date_ended'] = undefined;






export default AssetPriceHistoryInput;

