/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.24.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CloudProvidersProviderIdStorageEnginesGet200Response model module.
 * @module model/CloudProvidersProviderIdStorageEnginesGet200Response
 * @version 1.24.0
 */
class CloudProvidersProviderIdStorageEnginesGet200Response {
    /**
     * Constructs a new <code>CloudProvidersProviderIdStorageEnginesGet200Response</code>.
     * @alias module:model/CloudProvidersProviderIdStorageEnginesGet200Response
     * @param message {String} 
     */
    constructor(message) { 
        
        CloudProvidersProviderIdStorageEnginesGet200Response.initialize(this, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message) { 
        obj['message'] = message;
    }

    /**
     * Constructs a <code>CloudProvidersProviderIdStorageEnginesGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudProvidersProviderIdStorageEnginesGet200Response} obj Optional instance to populate.
     * @return {module:model/CloudProvidersProviderIdStorageEnginesGet200Response} The populated <code>CloudProvidersProviderIdStorageEnginesGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudProvidersProviderIdStorageEnginesGet200Response();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CloudProvidersProviderIdStorageEnginesGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CloudProvidersProviderIdStorageEnginesGet200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CloudProvidersProviderIdStorageEnginesGet200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

CloudProvidersProviderIdStorageEnginesGet200Response.RequiredProperties = ["message"];

/**
 * @member {String} message
 */
CloudProvidersProviderIdStorageEnginesGet200Response.prototype['message'] = undefined;

/**
 * @member {Object} data
 */
CloudProvidersProviderIdStorageEnginesGet200Response.prototype['data'] = undefined;






export default CloudProvidersProviderIdStorageEnginesGet200Response;

