/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CloudProvidersUpdate model module.
 * @module model/CloudProvidersUpdate
 * @version 1.25.0
 */
class CloudProvidersUpdate {
    /**
     * Constructs a new <code>CloudProvidersUpdate</code>.
     * Update schema for modifying CloudProvider
     * @alias module:model/CloudProvidersUpdate
     */
    constructor() { 
        
        CloudProvidersUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CloudProvidersUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloudProvidersUpdate} obj Optional instance to populate.
     * @return {module:model/CloudProvidersUpdate} The populated <code>CloudProvidersUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloudProvidersUpdate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parent_company')) {
                obj['parent_company'] = ApiClient.convertToType(data['parent_company'], 'String');
            }
            if (data.hasOwnProperty('marketing_homepage_url')) {
                obj['marketing_homepage_url'] = ApiClient.convertToType(data['marketing_homepage_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CloudProvidersUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CloudProvidersUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['parent_company'] && !(typeof data['parent_company'] === 'string' || data['parent_company'] instanceof String)) {
            throw new Error("Expected the field `parent_company` to be a primitive type in the JSON string but got " + data['parent_company']);
        }
        // ensure the json data is a string
        if (data['marketing_homepage_url'] && !(typeof data['marketing_homepage_url'] === 'string' || data['marketing_homepage_url'] instanceof String)) {
            throw new Error("Expected the field `marketing_homepage_url` to be a primitive type in the JSON string but got " + data['marketing_homepage_url']);
        }

        return true;
    }


}



/**
 * Required.
 * @member {String} name
 */
CloudProvidersUpdate.prototype['name'] = undefined;

/**
 * Optional.
 * @member {String} parent_company
 */
CloudProvidersUpdate.prototype['parent_company'] = undefined;

/**
 * Optional.
 * @member {String} marketing_homepage_url
 */
CloudProvidersUpdate.prototype['marketing_homepage_url'] = undefined;






export default CloudProvidersUpdate;

