/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.24.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompaniesInput model module.
 * @module model/CompaniesInput
 * @version 1.24.0
 */
class CompaniesInput {
    /**
     * Constructs a new <code>CompaniesInput</code>.
     * Input schema for creating Company
     * @alias module:model/CompaniesInput
     * @param companyHandle {String} 
     * @param companyDomain {String} 
     */
    constructor(companyHandle, companyDomain) { 
        
        CompaniesInput.initialize(this, companyHandle, companyDomain);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, companyHandle, companyDomain) { 
        obj['company_handle'] = companyHandle;
        obj['company_domain'] = companyDomain;
    }

    /**
     * Constructs a <code>CompaniesInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompaniesInput} obj Optional instance to populate.
     * @return {module:model/CompaniesInput} The populated <code>CompaniesInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompaniesInput();

            if (data.hasOwnProperty('industry_id')) {
                obj['industry_id'] = ApiClient.convertToType(data['industry_id'], 'Number');
            }
            if (data.hasOwnProperty('country_id')) {
                obj['country_id'] = ApiClient.convertToType(data['country_id'], 'Number');
            }
            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('company_description')) {
                obj['company_description'] = ApiClient.convertToType(data['company_description'], 'String');
            }
            if (data.hasOwnProperty('company_handle')) {
                obj['company_handle'] = ApiClient.convertToType(data['company_handle'], 'String');
            }
            if (data.hasOwnProperty('company_domain')) {
                obj['company_domain'] = ApiClient.convertToType(data['company_domain'], 'String');
            }
            if (data.hasOwnProperty('credits_balance')) {
                obj['credits_balance'] = ApiClient.convertToType(data['credits_balance'], 'Number');
            }
            if (data.hasOwnProperty('accepted_eula')) {
                obj['accepted_eula'] = ApiClient.convertToType(data['accepted_eula'], 'Boolean');
            }
            if (data.hasOwnProperty('stripe_account_id')) {
                obj['stripe_account_id'] = ApiClient.convertToType(data['stripe_account_id'], 'String');
            }
            if (data.hasOwnProperty('stripe_account_status')) {
                obj['stripe_account_status'] = ApiClient.convertToType(data['stripe_account_status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompaniesInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompaniesInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CompaniesInput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['company_name'] && !(typeof data['company_name'] === 'string' || data['company_name'] instanceof String)) {
            throw new Error("Expected the field `company_name` to be a primitive type in the JSON string but got " + data['company_name']);
        }
        // ensure the json data is a string
        if (data['company_description'] && !(typeof data['company_description'] === 'string' || data['company_description'] instanceof String)) {
            throw new Error("Expected the field `company_description` to be a primitive type in the JSON string but got " + data['company_description']);
        }
        // ensure the json data is a string
        if (data['company_handle'] && !(typeof data['company_handle'] === 'string' || data['company_handle'] instanceof String)) {
            throw new Error("Expected the field `company_handle` to be a primitive type in the JSON string but got " + data['company_handle']);
        }
        // ensure the json data is a string
        if (data['company_domain'] && !(typeof data['company_domain'] === 'string' || data['company_domain'] instanceof String)) {
            throw new Error("Expected the field `company_domain` to be a primitive type in the JSON string but got " + data['company_domain']);
        }
        // ensure the json data is a string
        if (data['stripe_account_id'] && !(typeof data['stripe_account_id'] === 'string' || data['stripe_account_id'] instanceof String)) {
            throw new Error("Expected the field `stripe_account_id` to be a primitive type in the JSON string but got " + data['stripe_account_id']);
        }
        // ensure the json data is a string
        if (data['stripe_account_status'] && !(typeof data['stripe_account_status'] === 'string' || data['stripe_account_status'] instanceof String)) {
            throw new Error("Expected the field `stripe_account_status` to be a primitive type in the JSON string but got " + data['stripe_account_status']);
        }

        return true;
    }


}

CompaniesInput.RequiredProperties = ["company_handle", "company_domain"];

/**
 * @member {Number} industry_id
 */
CompaniesInput.prototype['industry_id'] = undefined;

/**
 * @member {Number} country_id
 */
CompaniesInput.prototype['country_id'] = undefined;

/**
 * @member {String} company_name
 */
CompaniesInput.prototype['company_name'] = undefined;

/**
 * @member {String} company_description
 */
CompaniesInput.prototype['company_description'] = undefined;

/**
 * @member {String} company_handle
 */
CompaniesInput.prototype['company_handle'] = undefined;

/**
 * @member {String} company_domain
 */
CompaniesInput.prototype['company_domain'] = undefined;

/**
 * Current balance of credits for this company (buyer)
 * @member {Number} credits_balance
 */
CompaniesInput.prototype['credits_balance'] = undefined;

/**
 * @member {Boolean} accepted_eula
 */
CompaniesInput.prototype['accepted_eula'] = undefined;

/**
 * Stripe Connect account ID for marketplace sellers
 * @member {String} stripe_account_id
 */
CompaniesInput.prototype['stripe_account_id'] = undefined;

/**
 * Status of the Stripe account (verified, pending, etc.)
 * @member {String} stripe_account_status
 */
CompaniesInput.prototype['stripe_account_status'] = undefined;






export default CompaniesInput;

