/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData model module.
 * @module model/CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData
 * @version 0.0.0
 */
class CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData {
    /**
     * Constructs a new <code>CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData</code>.
     * @alias module:model/CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData
     * @param alertId {String} ID of the deleted alerts
     */
    constructor(alertId) { 
        
        CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData.initialize(this, alertId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, alertId) { 
        obj['alert_id'] = alertId;
    }

    /**
     * Constructs a <code>CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData} obj Optional instance to populate.
     * @return {module:model/CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData} The populated <code>CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData();

            if (data.hasOwnProperty('alert_id')) {
                obj['alert_id'] = ApiClient.convertToType(data['alert_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['alert_id'] && !(typeof data['alert_id'] === 'string' || data['alert_id'] instanceof String)) {
            throw new Error("Expected the field `alert_id` to be a primitive type in the JSON string but got " + data['alert_id']);
        }

        return true;
    }


}

CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData.RequiredProperties = ["alert_id"];

/**
 * ID of the deleted alerts
 * @member {String} alert_id
 */
CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData.prototype['alert_id'] = undefined;






export default CompaniesCompanyIdUsersUserIdAlertsAlertIdDelete200ResponseData;

