/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateApiKeys200ResponseData model module.
 * @module model/CreateApiKeys200ResponseData
 * @version 1.25.0
 */
class CreateApiKeys200ResponseData {
    /**
     * Constructs a new <code>CreateApiKeys200ResponseData</code>.
     * @alias module:model/CreateApiKeys200ResponseData
     * @param apiKeyId {String} ID of the created api_keys
     */
    constructor(apiKeyId) { 
        
        CreateApiKeys200ResponseData.initialize(this, apiKeyId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, apiKeyId) { 
        obj['api_key_id'] = apiKeyId;
    }

    /**
     * Constructs a <code>CreateApiKeys200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateApiKeys200ResponseData} obj Optional instance to populate.
     * @return {module:model/CreateApiKeys200ResponseData} The populated <code>CreateApiKeys200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateApiKeys200ResponseData();

            if (data.hasOwnProperty('api_key_id')) {
                obj['api_key_id'] = ApiClient.convertToType(data['api_key_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateApiKeys200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateApiKeys200ResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateApiKeys200ResponseData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['api_key_id'] && !(typeof data['api_key_id'] === 'string' || data['api_key_id'] instanceof String)) {
            throw new Error("Expected the field `api_key_id` to be a primitive type in the JSON string but got " + data['api_key_id']);
        }

        return true;
    }


}

CreateApiKeys200ResponseData.RequiredProperties = ["api_key_id"];

/**
 * ID of the created api_keys
 * @member {String} api_key_id
 */
CreateApiKeys200ResponseData.prototype['api_key_id'] = undefined;






export default CreateApiKeys200ResponseData;

