/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreatePostgenIntegrations200ResponseData model module.
 * @module model/CreatePostgenIntegrations200ResponseData
 * @version 1.25.0
 */
class CreatePostgenIntegrations200ResponseData {
    /**
     * Constructs a new <code>CreatePostgenIntegrations200ResponseData</code>.
     * @alias module:model/CreatePostgenIntegrations200ResponseData
     * @param integrationId {String} ID of the created postgen_integrations
     */
    constructor(integrationId) { 
        
        CreatePostgenIntegrations200ResponseData.initialize(this, integrationId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, integrationId) { 
        obj['integration_id'] = integrationId;
    }

    /**
     * Constructs a <code>CreatePostgenIntegrations200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePostgenIntegrations200ResponseData} obj Optional instance to populate.
     * @return {module:model/CreatePostgenIntegrations200ResponseData} The populated <code>CreatePostgenIntegrations200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePostgenIntegrations200ResponseData();

            if (data.hasOwnProperty('integration_id')) {
                obj['integration_id'] = ApiClient.convertToType(data['integration_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreatePostgenIntegrations200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreatePostgenIntegrations200ResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreatePostgenIntegrations200ResponseData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['integration_id'] && !(typeof data['integration_id'] === 'string' || data['integration_id'] instanceof String)) {
            throw new Error("Expected the field `integration_id` to be a primitive type in the JSON string but got " + data['integration_id']);
        }

        return true;
    }


}

CreatePostgenIntegrations200ResponseData.RequiredProperties = ["integration_id"];

/**
 * ID of the created postgen_integrations
 * @member {String} integration_id
 */
CreatePostgenIntegrations200ResponseData.prototype['integration_id'] = undefined;






export default CreatePostgenIntegrations200ResponseData;

