/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteConnections200ResponseData model module.
 * @module model/DeleteConnections200ResponseData
 * @version 1.25.0
 */
class DeleteConnections200ResponseData {
    /**
     * Constructs a new <code>DeleteConnections200ResponseData</code>.
     * @alias module:model/DeleteConnections200ResponseData
     * @param connectionId {String} ID of the deleted connections
     */
    constructor(connectionId) { 
        
        DeleteConnections200ResponseData.initialize(this, connectionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, connectionId) { 
        obj['connection_id'] = connectionId;
    }

    /**
     * Constructs a <code>DeleteConnections200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteConnections200ResponseData} obj Optional instance to populate.
     * @return {module:model/DeleteConnections200ResponseData} The populated <code>DeleteConnections200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteConnections200ResponseData();

            if (data.hasOwnProperty('connection_id')) {
                obj['connection_id'] = ApiClient.convertToType(data['connection_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteConnections200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteConnections200ResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeleteConnections200ResponseData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['connection_id'] && !(typeof data['connection_id'] === 'string' || data['connection_id'] instanceof String)) {
            throw new Error("Expected the field `connection_id` to be a primitive type in the JSON string but got " + data['connection_id']);
        }

        return true;
    }


}

DeleteConnections200ResponseData.RequiredProperties = ["connection_id"];

/**
 * ID of the deleted connections
 * @member {String} connection_id
 */
DeleteConnections200ResponseData.prototype['connection_id'] = undefined;






export default DeleteConnections200ResponseData;

