/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteAssets200ResponseData model module.
 * @module model/DeleteAssets200ResponseData
 * @version 1.25.0
 */
class DeleteAssets200ResponseData {
    /**
     * Constructs a new <code>DeleteAssets200ResponseData</code>.
     * @alias module:model/DeleteAssets200ResponseData
     * @param assetId {String} ID of the deleted assets
     */
    constructor(assetId) { 
        
        DeleteAssets200ResponseData.initialize(this, assetId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assetId) { 
        obj['asset_id'] = assetId;
    }

    /**
     * Constructs a <code>DeleteAssets200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteAssets200ResponseData} obj Optional instance to populate.
     * @return {module:model/DeleteAssets200ResponseData} The populated <code>DeleteAssets200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteAssets200ResponseData();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteAssets200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteAssets200ResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeleteAssets200ResponseData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['asset_id'] && !(typeof data['asset_id'] === 'string' || data['asset_id'] instanceof String)) {
            throw new Error("Expected the field `asset_id` to be a primitive type in the JSON string but got " + data['asset_id']);
        }

        return true;
    }


}

DeleteAssets200ResponseData.RequiredProperties = ["asset_id"];

/**
 * ID of the deleted assets
 * @member {String} asset_id
 */
DeleteAssets200ResponseData.prototype['asset_id'] = undefined;






export default DeleteAssets200ResponseData;

