/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Favorites model module.
 * @module model/Favorites
 * @version 1.25.0
 */
class Favorites {
    /**
     * Constructs a new <code>Favorites</code>.
     * A saved marketplace asset in a user&#39;s favorites library
     * @alias module:model/Favorites
     * @param assetId {String} References assets.asset_id — A published analytics asset — a calculation or visualization built on a data connection. See GET /assets for valid values. Required.
     * @param companyId {String} References companies.company_id — A Spartera seller or buyer company account. See GET /companies for valid values. Required.
     * @param priority {Number} User-defined priority for sorting (higher = more important)
     */
    constructor(assetId, companyId, priority) { 
        
        Favorites.initialize(this, assetId, companyId, priority);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assetId, companyId, priority) { 
        obj['asset_id'] = assetId;
        obj['company_id'] = companyId;
        obj['priority'] = priority;
    }

    /**
     * Constructs a <code>Favorites</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Favorites} obj Optional instance to populate.
     * @return {module:model/Favorites} The populated <code>Favorites</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Favorites();

            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'Date');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'Date');
            }
            if (data.hasOwnProperty('favorite_id')) {
                obj['favorite_id'] = ApiClient.convertToType(data['favorite_id'], 'Number');
            }
            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('company_id')) {
                obj['company_id'] = ApiClient.convertToType(data['company_id'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Favorites</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Favorites</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Favorites.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['asset_id'] && !(typeof data['asset_id'] === 'string' || data['asset_id'] instanceof String)) {
            throw new Error("Expected the field `asset_id` to be a primitive type in the JSON string but got " + data['asset_id']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        // ensure the json data is a string
        if (data['company_id'] && !(typeof data['company_id'] === 'string' || data['company_id'] instanceof String)) {
            throw new Error("Expected the field `company_id` to be a primitive type in the JSON string but got " + data['company_id']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }

        return true;
    }


}

Favorites.RequiredProperties = ["asset_id", "company_id", "priority"];

/**
 * Optional.
 * @member {Date} date_created
 */
Favorites.prototype['date_created'] = undefined;

/**
 * Optional.
 * @member {Date} last_updated
 */
Favorites.prototype['last_updated'] = undefined;

/**
 * Auto-generated unique identifier.
 * @member {Number} favorite_id
 */
Favorites.prototype['favorite_id'] = undefined;

/**
 * References assets.asset_id — A published analytics asset — a calculation or visualization built on a data connection. See GET /assets for valid values. Required.
 * @member {String} asset_id
 */
Favorites.prototype['asset_id'] = undefined;

/**
 * References users.user_id — An individual user account within a company. See GET /users for valid values. Optional.
 * @member {String} user_id
 */
Favorites.prototype['user_id'] = undefined;

/**
 * References companies.company_id — A Spartera seller or buyer company account. See GET /companies for valid values. Required.
 * @member {String} company_id
 */
Favorites.prototype['company_id'] = undefined;

/**
 * Optional user notes about this favorite
 * @member {String} notes
 */
Favorites.prototype['notes'] = undefined;

/**
 * Optional category for organizing favorites (e.g., 'Work', 'Research')
 * @member {String} category
 */
Favorites.prototype['category'] = undefined;

/**
 * User-defined priority for sorting (higher = more important)
 * @member {Number} priority
 */
Favorites.prototype['priority'] = undefined;






export default Favorites;

