/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Industries model module.
 * @module model/Industries
 * @version 1.25.0
 */
class Industries {
    /**
     * Constructs a new <code>Industries</code>.
     * Available industry categories for asset classification. Based on US NAISC codes.
     * @alias module:model/Industries
     * @param industryName {String} Required. Must be unique.
     * @param shortName {String} Required.
     */
    constructor(industryName, shortName) { 
        
        Industries.initialize(this, industryName, shortName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, industryName, shortName) { 
        obj['industry_name'] = industryName;
        obj['short_name'] = shortName;
    }

    /**
     * Constructs a <code>Industries</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Industries} obj Optional instance to populate.
     * @return {module:model/Industries} The populated <code>Industries</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Industries();

            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'Date');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'Date');
            }
            if (data.hasOwnProperty('industry_id')) {
                obj['industry_id'] = ApiClient.convertToType(data['industry_id'], 'Number');
            }
            if (data.hasOwnProperty('industry_name')) {
                obj['industry_name'] = ApiClient.convertToType(data['industry_name'], 'String');
            }
            if (data.hasOwnProperty('short_name')) {
                obj['short_name'] = ApiClient.convertToType(data['short_name'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('naisc_code')) {
                obj['naisc_code'] = ApiClient.convertToType(data['naisc_code'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Industries</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Industries</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Industries.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['industry_name'] && !(typeof data['industry_name'] === 'string' || data['industry_name'] instanceof String)) {
            throw new Error("Expected the field `industry_name` to be a primitive type in the JSON string but got " + data['industry_name']);
        }
        // ensure the json data is a string
        if (data['short_name'] && !(typeof data['short_name'] === 'string' || data['short_name'] instanceof String)) {
            throw new Error("Expected the field `short_name` to be a primitive type in the JSON string but got " + data['short_name']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

Industries.RequiredProperties = ["industry_name", "short_name"];

/**
 * Optional.
 * @member {Date} date_created
 */
Industries.prototype['date_created'] = undefined;

/**
 * Optional.
 * @member {Date} last_updated
 */
Industries.prototype['last_updated'] = undefined;

/**
 * Auto-generated unique identifier.
 * @member {Number} industry_id
 */
Industries.prototype['industry_id'] = undefined;

/**
 * Required. Must be unique.
 * @member {String} industry_name
 */
Industries.prototype['industry_name'] = undefined;

/**
 * Required.
 * @member {String} short_name
 */
Industries.prototype['short_name'] = undefined;

/**
 * Optional.
 * @member {String} slug
 */
Industries.prototype['slug'] = undefined;

/**
 * Optional.
 * @member {Number} naisc_code
 */
Industries.prototype['naisc_code'] = undefined;

/**
 * Optional.
 * @member {String} description
 */
Industries.prototype['description'] = undefined;






export default Industries;

