/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobFunctionsInput model module.
 * @module model/JobFunctionsInput
 * @version 1.25.0
 */
class JobFunctionsInput {
    /**
     * Constructs a new <code>JobFunctionsInput</code>.
     * Input schema for creating JobFunction
     * @alias module:model/JobFunctionsInput
     * @param name {String} Required. Must be unique.
     */
    constructor(name) { 
        
        JobFunctionsInput.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>JobFunctionsInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobFunctionsInput} obj Optional instance to populate.
     * @return {module:model/JobFunctionsInput} The populated <code>JobFunctionsInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobFunctionsInput();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobFunctionsInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobFunctionsInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JobFunctionsInput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

JobFunctionsInput.RequiredProperties = ["name"];

/**
 * Required. Must be unique.
 * @member {String} name
 */
JobFunctionsInput.prototype['name'] = undefined;






export default JobFunctionsInput;

