/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostPublications model module.
 * @module model/PostPublications
 * @version 1.25.0
 */
class PostPublications {
    /**
     * Constructs a new <code>PostPublications</code>.
     * Tracks where posts have been published to external platforms
     * @alias module:model/PostPublications
     * @param postId {String} Post that was published
     * @param companyId {String} Company this publication belongs to
     * @param platform {String} Platform identifier (beehiiv, wordpress, etc)
     * @param status {String} Status: published, failed, deleted
     */
    constructor(postId, companyId, platform, status) { 
        
        PostPublications.initialize(this, postId, companyId, platform, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, postId, companyId, platform, status) { 
        obj['post_id'] = postId;
        obj['company_id'] = companyId;
        obj['platform'] = platform;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>PostPublications</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostPublications} obj Optional instance to populate.
     * @return {module:model/PostPublications} The populated <code>PostPublications</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostPublications();

            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'Date');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'Date');
            }
            if (data.hasOwnProperty('publication_id')) {
                obj['publication_id'] = ApiClient.convertToType(data['publication_id'], 'String');
            }
            if (data.hasOwnProperty('post_id')) {
                obj['post_id'] = ApiClient.convertToType(data['post_id'], 'String');
            }
            if (data.hasOwnProperty('company_id')) {
                obj['company_id'] = ApiClient.convertToType(data['company_id'], 'String');
            }
            if (data.hasOwnProperty('integration_id')) {
                obj['integration_id'] = ApiClient.convertToType(data['integration_id'], 'String');
            }
            if (data.hasOwnProperty('platform')) {
                obj['platform'] = ApiClient.convertToType(data['platform'], 'String');
            }
            if (data.hasOwnProperty('external_post_id')) {
                obj['external_post_id'] = ApiClient.convertToType(data['external_post_id'], 'String');
            }
            if (data.hasOwnProperty('external_post_url')) {
                obj['external_post_url'] = ApiClient.convertToType(data['external_post_url'], 'String');
            }
            if (data.hasOwnProperty('published_at')) {
                obj['published_at'] = ApiClient.convertToType(data['published_at'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('error_message')) {
                obj['error_message'] = ApiClient.convertToType(data['error_message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostPublications</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostPublications</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostPublications.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['publication_id'] && !(typeof data['publication_id'] === 'string' || data['publication_id'] instanceof String)) {
            throw new Error("Expected the field `publication_id` to be a primitive type in the JSON string but got " + data['publication_id']);
        }
        // ensure the json data is a string
        if (data['post_id'] && !(typeof data['post_id'] === 'string' || data['post_id'] instanceof String)) {
            throw new Error("Expected the field `post_id` to be a primitive type in the JSON string but got " + data['post_id']);
        }
        // ensure the json data is a string
        if (data['company_id'] && !(typeof data['company_id'] === 'string' || data['company_id'] instanceof String)) {
            throw new Error("Expected the field `company_id` to be a primitive type in the JSON string but got " + data['company_id']);
        }
        // ensure the json data is a string
        if (data['integration_id'] && !(typeof data['integration_id'] === 'string' || data['integration_id'] instanceof String)) {
            throw new Error("Expected the field `integration_id` to be a primitive type in the JSON string but got " + data['integration_id']);
        }
        // ensure the json data is a string
        if (data['platform'] && !(typeof data['platform'] === 'string' || data['platform'] instanceof String)) {
            throw new Error("Expected the field `platform` to be a primitive type in the JSON string but got " + data['platform']);
        }
        // ensure the json data is a string
        if (data['external_post_id'] && !(typeof data['external_post_id'] === 'string' || data['external_post_id'] instanceof String)) {
            throw new Error("Expected the field `external_post_id` to be a primitive type in the JSON string but got " + data['external_post_id']);
        }
        // ensure the json data is a string
        if (data['external_post_url'] && !(typeof data['external_post_url'] === 'string' || data['external_post_url'] instanceof String)) {
            throw new Error("Expected the field `external_post_url` to be a primitive type in the JSON string but got " + data['external_post_url']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['error_message'] && !(typeof data['error_message'] === 'string' || data['error_message'] instanceof String)) {
            throw new Error("Expected the field `error_message` to be a primitive type in the JSON string but got " + data['error_message']);
        }

        return true;
    }


}

PostPublications.RequiredProperties = ["post_id", "company_id", "platform", "status"];

/**
 * Optional.
 * @member {Date} date_created
 */
PostPublications.prototype['date_created'] = undefined;

/**
 * Optional.
 * @member {Date} last_updated
 */
PostPublications.prototype['last_updated'] = undefined;

/**
 * Unique identifier.
 * @member {String} publication_id
 */
PostPublications.prototype['publication_id'] = undefined;

/**
 * Post that was published
 * @member {String} post_id
 */
PostPublications.prototype['post_id'] = undefined;

/**
 * Company this publication belongs to
 * @member {String} company_id
 */
PostPublications.prototype['company_id'] = undefined;

/**
 * Integration used for publishing
 * @member {String} integration_id
 */
PostPublications.prototype['integration_id'] = undefined;

/**
 * Platform identifier (beehiiv, wordpress, etc)
 * @member {String} platform
 */
PostPublications.prototype['platform'] = undefined;

/**
 * ID of the post on the external platform
 * @member {String} external_post_id
 */
PostPublications.prototype['external_post_id'] = undefined;

/**
 * URL to view the post on the external platform
 * @member {String} external_post_url
 */
PostPublications.prototype['external_post_url'] = undefined;

/**
 * When the post was published to this platform
 * @member {Date} published_at
 */
PostPublications.prototype['published_at'] = undefined;

/**
 * Status: published, failed, deleted
 * @member {String} status
 */
PostPublications.prototype['status'] = undefined;

/**
 * Error message if publication failed
 * @member {String} error_message
 */
PostPublications.prototype['error_message'] = undefined;






export default PostPublications;

