/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StorageEngines model module.
 * @module model/StorageEngines
 * @version 1.25.0
 */
class StorageEngines {
    /**
     * Constructs a new <code>StorageEngines</code>.
     * Fact table of all the different storage engines we support
     * @alias module:model/StorageEngines
     * @param providerId {Number} References cloud_providers.provider_id — Supported cloud platforms and database engines available for connections. See GET /cloud_providers for valid values. Required.
     * @param serviceName {String} Required.
     * @param engineType {module:model/StorageEngines.EngineTypeEnum} Required. One of: EDW, LLM, RDBMS, OBJ, API_MODEL, … (6 total).
     */
    constructor(providerId, serviceName, engineType) { 
        
        StorageEngines.initialize(this, providerId, serviceName, engineType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, providerId, serviceName, engineType) { 
        obj['provider_id'] = providerId;
        obj['service_name'] = serviceName;
        obj['engine_type'] = engineType;
    }

    /**
     * Constructs a <code>StorageEngines</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StorageEngines} obj Optional instance to populate.
     * @return {module:model/StorageEngines} The populated <code>StorageEngines</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageEngines();

            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'Date');
            }
            if (data.hasOwnProperty('last_updated')) {
                obj['last_updated'] = ApiClient.convertToType(data['last_updated'], 'Date');
            }
            if (data.hasOwnProperty('engine_id')) {
                obj['engine_id'] = ApiClient.convertToType(data['engine_id'], 'Number');
            }
            if (data.hasOwnProperty('provider_id')) {
                obj['provider_id'] = ApiClient.convertToType(data['provider_id'], 'Number');
            }
            if (data.hasOwnProperty('service_name')) {
                obj['service_name'] = ApiClient.convertToType(data['service_name'], 'String');
            }
            if (data.hasOwnProperty('engine_type')) {
                obj['engine_type'] = ApiClient.convertToType(data['engine_type'], 'String');
            }
            if (data.hasOwnProperty('integration_complete')) {
                obj['integration_complete'] = ApiClient.convertToType(data['integration_complete'], 'Boolean');
            }
            if (data.hasOwnProperty('test_func_complete')) {
                obj['test_func_complete'] = ApiClient.convertToType(data['test_func_complete'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StorageEngines</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StorageEngines</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StorageEngines.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['service_name'] && !(typeof data['service_name'] === 'string' || data['service_name'] instanceof String)) {
            throw new Error("Expected the field `service_name` to be a primitive type in the JSON string but got " + data['service_name']);
        }
        // ensure the json data is a string
        if (data['engine_type'] && !(typeof data['engine_type'] === 'string' || data['engine_type'] instanceof String)) {
            throw new Error("Expected the field `engine_type` to be a primitive type in the JSON string but got " + data['engine_type']);
        }

        return true;
    }


}

StorageEngines.RequiredProperties = ["provider_id", "service_name", "engine_type"];

/**
 * Optional.
 * @member {Date} date_created
 */
StorageEngines.prototype['date_created'] = undefined;

/**
 * Optional.
 * @member {Date} last_updated
 */
StorageEngines.prototype['last_updated'] = undefined;

/**
 * Unique identifier.
 * @member {Number} engine_id
 */
StorageEngines.prototype['engine_id'] = undefined;

/**
 * References cloud_providers.provider_id — Supported cloud platforms and database engines available for connections. See GET /cloud_providers for valid values. Required.
 * @member {Number} provider_id
 */
StorageEngines.prototype['provider_id'] = undefined;

/**
 * Required.
 * @member {String} service_name
 */
StorageEngines.prototype['service_name'] = undefined;

/**
 * Required. One of: EDW, LLM, RDBMS, OBJ, API_MODEL, … (6 total).
 * @member {module:model/StorageEngines.EngineTypeEnum} engine_type
 */
StorageEngines.prototype['engine_type'] = undefined;

/**
 * Optional.
 * @member {Boolean} integration_complete
 */
StorageEngines.prototype['integration_complete'] = undefined;

/**
 * Optional.
 * @member {Boolean} test_func_complete
 */
StorageEngines.prototype['test_func_complete'] = undefined;





/**
 * Allowed values for the <code>engine_type</code> property.
 * @enum {String}
 * @readonly
 */
StorageEngines['EngineTypeEnum'] = {

    /**
     * value: "EDW"
     * @const
     */
    "EDW": "EDW",

    /**
     * value: "LLM"
     * @const
     */
    "LLM": "LLM",

    /**
     * value: "RDBMS"
     * @const
     */
    "RDBMS": "RDBMS",

    /**
     * value: "OBJ"
     * @const
     */
    "OBJ": "OBJ",

    /**
     * value: "API_MODEL"
     * @const
     */
    "API_MODEL": "API_MODEL",

    /**
     * value: "EXTERNAL_API"
     * @const
     */
    "EXTERNAL_API": "EXTERNAL_API"
};



export default StorageEngines;

