/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateCompanies200ResponseData model module.
 * @module model/UpdateCompanies200ResponseData
 * @version 1.25.0
 */
class UpdateCompanies200ResponseData {
    /**
     * Constructs a new <code>UpdateCompanies200ResponseData</code>.
     * @alias module:model/UpdateCompanies200ResponseData
     * @param companyId {String} ID of the updated companies
     */
    constructor(companyId) { 
        
        UpdateCompanies200ResponseData.initialize(this, companyId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, companyId) { 
        obj['company_id'] = companyId;
    }

    /**
     * Constructs a <code>UpdateCompanies200ResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateCompanies200ResponseData} obj Optional instance to populate.
     * @return {module:model/UpdateCompanies200ResponseData} The populated <code>UpdateCompanies200ResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateCompanies200ResponseData();

            if (data.hasOwnProperty('company_id')) {
                obj['company_id'] = ApiClient.convertToType(data['company_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateCompanies200ResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateCompanies200ResponseData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateCompanies200ResponseData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['company_id'] && !(typeof data['company_id'] === 'string' || data['company_id'] instanceof String)) {
            throw new Error("Expected the field `company_id` to be a primitive type in the JSON string but got " + data['company_id']);
        }

        return true;
    }


}

UpdateCompanies200ResponseData.RequiredProperties = ["company_id"];

/**
 * ID of the updated companies
 * @member {String} company_id
 */
UpdateCompanies200ResponseData.prototype['company_id'] = undefined;






export default UpdateCompanies200ResponseData;

