/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AlertsInput from '../model/AlertsInput';
import AlertsUpdate from '../model/AlertsUpdate';
import CreateAlerts200Response from '../model/CreateAlerts200Response';
import DeleteAlerts200Response from '../model/DeleteAlerts200Response';
import GetAlertsById200Response from '../model/GetAlertsById200Response';
import InlineObject from '../model/InlineObject';
import InlineObject1 from '../model/InlineObject1';
import InlineObject2 from '../model/InlineObject2';
import InlineObject3 from '../model/InlineObject3';
import InlineObject4 from '../model/InlineObject4';
import InlineObject5 from '../model/InlineObject5';
import InlineObject6 from '../model/InlineObject6';
import InlineObject7 from '../model/InlineObject7';
import UpdateAlerts200Response from '../model/UpdateAlerts200Response';

/**
* Alerts service.
* @module api/AlertsApi
* @version 1.25.0
*/
export default class AlertsApi {

    /**
    * Constructs a new AlertsApi. 
    * @alias module:api/AlertsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createAlerts operation.
     * @callback module:api/AlertsApi~createAlertsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateAlerts200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * POST /companies/{company_id}/users/{user_id}/alerts
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {module:model/AlertsInput} alertsInput 
     * @param {module:api/AlertsApi~createAlertsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateAlerts200Response}
     */
    createAlerts(companyId, userId, alertsInput, callback) {
      let postBody = alertsInput;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling createAlerts");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling createAlerts");
      }
      // verify the required parameter 'alertsInput' is set
      if (alertsInput === undefined || alertsInput === null) {
        throw new Error("Missing the required parameter 'alertsInput' when calling createAlerts");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateAlerts200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/alerts', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteAlerts operation.
     * @callback module:api/AlertsApi~deleteAlertsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeleteAlerts200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete single alert by ID
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} alertId Unique identifier for the Alert
     * @param {module:api/AlertsApi~deleteAlertsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeleteAlerts200Response}
     */
    deleteAlerts(companyId, userId, alertId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling deleteAlerts");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling deleteAlerts");
      }
      // verify the required parameter 'alertId' is set
      if (alertId === undefined || alertId === null) {
        throw new Error("Missing the required parameter 'alertId' when calling deleteAlerts");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'alert_id': alertId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeleteAlerts200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/alerts/{alert_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlertsById operation.
     * @callback module:api/AlertsApi~getAlertsByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAlertsById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of all alerts for a specific user
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {module:api/AlertsApi~getAlertsByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAlertsById200Response}
     */
    getAlertsById(companyId, userId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getAlertsById");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getAlertsById");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAlertsById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/alerts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlertsByIdAssetAll operation.
     * @callback module:api/AlertsApi~getAlertsByIdAssetAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAlertsById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all alerts for a specific asset
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} assetId Unique identifier for the Asset
     * @param {module:api/AlertsApi~getAlertsByIdAssetAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAlertsById200Response}
     */
    getAlertsByIdAssetAll(companyId, userId, assetId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getAlertsByIdAssetAll");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getAlertsByIdAssetAll");
      }
      // verify the required parameter 'assetId' is set
      if (assetId === undefined || assetId === null) {
        throw new Error("Missing the required parameter 'assetId' when calling getAlertsByIdAssetAll");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'asset_id': assetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAlertsById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/alerts/asset/{asset_id}/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlertsByIdUsers operation.
     * @callback module:api/AlertsApi~getAlertsByIdUsersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAlertsById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get single alert by ID
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} alertId Unique identifier for the Alert
     * @param {module:api/AlertsApi~getAlertsByIdUsersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAlertsById200Response}
     */
    getAlertsByIdUsers(companyId, userId, alertId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getAlertsByIdUsers");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getAlertsByIdUsers");
      }
      // verify the required parameter 'alertId' is set
      if (alertId === undefined || alertId === null) {
        throw new Error("Missing the required parameter 'alertId' when calling getAlertsByIdUsers");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'alert_id': alertId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAlertsById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/alerts/{alert_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAlertsByIdUsersAsset operation.
     * @callback module:api/AlertsApi~getAlertsByIdUsersAssetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAlertsById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all alerts for a specific asset (by user)
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} assetId Unique identifier for the Asset
     * @param {module:api/AlertsApi~getAlertsByIdUsersAssetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAlertsById200Response}
     */
    getAlertsByIdUsersAsset(companyId, userId, assetId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getAlertsByIdUsersAsset");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getAlertsByIdUsersAsset");
      }
      // verify the required parameter 'assetId' is set
      if (assetId === undefined || assetId === null) {
        throw new Error("Missing the required parameter 'assetId' when calling getAlertsByIdUsersAsset");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'asset_id': assetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAlertsById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/alerts/asset/{asset_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateAlerts operation.
     * @callback module:api/AlertsApi~updateAlertsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UpdateAlerts200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an existing alert by ID
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} alertId Unique identifier for the Alert
     * @param {module:model/AlertsUpdate} alertsUpdate 
     * @param {module:api/AlertsApi~updateAlertsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UpdateAlerts200Response}
     */
    updateAlerts(companyId, userId, alertId, alertsUpdate, callback) {
      let postBody = alertsUpdate;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling updateAlerts");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling updateAlerts");
      }
      // verify the required parameter 'alertId' is set
      if (alertId === undefined || alertId === null) {
        throw new Error("Missing the required parameter 'alertId' when calling updateAlerts");
      }
      // verify the required parameter 'alertsUpdate' is set
      if (alertsUpdate === undefined || alertsUpdate === null) {
        throw new Error("Missing the required parameter 'alertsUpdate' when calling updateAlerts");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'alert_id': alertId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UpdateAlerts200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/alerts/{alert_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
