/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiKeysInput from '../model/ApiKeysInput';
import ApiKeysUpdate from '../model/ApiKeysUpdate';
import CreateApiKeys200Response from '../model/CreateApiKeys200Response';
import DeleteApiKeys200Response from '../model/DeleteApiKeys200Response';
import GetApiKeysById200Response from '../model/GetApiKeysById200Response';
import InlineObject from '../model/InlineObject';
import InlineObject1 from '../model/InlineObject1';
import InlineObject2 from '../model/InlineObject2';
import InlineObject3 from '../model/InlineObject3';
import InlineObject4 from '../model/InlineObject4';
import InlineObject5 from '../model/InlineObject5';
import InlineObject6 from '../model/InlineObject6';
import InlineObject7 from '../model/InlineObject7';
import ListApiKeys200Response from '../model/ListApiKeys200Response';
import UpdateApiKeys200Response from '../model/UpdateApiKeys200Response';

/**
* APIKeys service.
* @module api/APIKeysApi
* @version 1.25.0
*/
export default class APIKeysApi {

    /**
    * Constructs a new APIKeysApi. 
    * @alias module:api/APIKeysApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createApiKeys operation.
     * @callback module:api/APIKeysApi~createApiKeysCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateApiKeys200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create single API key.     Returns the actual sk_ key (only time it's exposed) and api_key_id for future operations.
     * @param {String} companyId Unique identifier for the Company
     * @param {module:model/ApiKeysInput} apiKeysInput 
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] Page number for pagination
     * @param {Number} [limit = 20)] Number of items per page
     * @param {String} [sortBy] Field to sort by
     * @param {module:model/String} [sortOrder = 'desc')] Sort order (ascending or descending)
     * @param {String} [search] Search term to filter results
     * @param {module:api/APIKeysApi~createApiKeysCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateApiKeys200Response}
     */
    createApiKeys(companyId, apiKeysInput, opts, callback) {
      opts = opts || {};
      let postBody = apiKeysInput;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling createApiKeys");
      }
      // verify the required parameter 'apiKeysInput' is set
      if (apiKeysInput === undefined || apiKeysInput === null) {
        throw new Error("Missing the required parameter 'apiKeysInput' when calling createApiKeys");
      }

      let pathParams = {
        'company_id': companyId
      };
      let queryParams = {
        'page': opts['page'],
        'limit': opts['limit'],
        'sort_by': opts['sortBy'],
        'sort_order': opts['sortOrder'],
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateApiKeys200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/api-keys', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the createApiKeysApiKeysRevoke operation.
     * @callback module:api/APIKeysApi~createApiKeysApiKeysRevokeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateApiKeys200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Explicitly revoke an API key with reason tracking.     This is different from delete as it includes revocation metadata.
     * @param {String} companyId Unique identifier for the Company
     * @param {String} apiKeyId Unique identifier for the Api Key
     * @param {module:model/ApiKeysInput} apiKeysInput 
     * @param {module:api/APIKeysApi~createApiKeysApiKeysRevokeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateApiKeys200Response}
     */
    createApiKeysApiKeysRevoke(companyId, apiKeyId, apiKeysInput, callback) {
      let postBody = apiKeysInput;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling createApiKeysApiKeysRevoke");
      }
      // verify the required parameter 'apiKeyId' is set
      if (apiKeyId === undefined || apiKeyId === null) {
        throw new Error("Missing the required parameter 'apiKeyId' when calling createApiKeysApiKeysRevoke");
      }
      // verify the required parameter 'apiKeysInput' is set
      if (apiKeysInput === undefined || apiKeysInput === null) {
        throw new Error("Missing the required parameter 'apiKeysInput' when calling createApiKeysApiKeysRevoke");
      }

      let pathParams = {
        'company_id': companyId,
        'api_key_id': apiKeyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateApiKeys200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/api-keys/{api_key_id}/revoke', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteApiKeys operation.
     * @callback module:api/APIKeysApi~deleteApiKeysCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeleteApiKeys200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete (deactivate) single API key by api_key_id.     Uses the api_key_id returned during creation for clean identification.     Fixed to use correct primary key lookup.
     * @param {String} companyId Unique identifier for the Company
     * @param {String} apiKeyId Unique identifier for the Api Key
     * @param {module:api/APIKeysApi~deleteApiKeysCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeleteApiKeys200Response}
     */
    deleteApiKeys(companyId, apiKeyId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling deleteApiKeys");
      }
      // verify the required parameter 'apiKeyId' is set
      if (apiKeyId === undefined || apiKeyId === null) {
        throw new Error("Missing the required parameter 'apiKeyId' when calling deleteApiKeys");
      }

      let pathParams = {
        'company_id': companyId,
        'api_key_id': apiKeyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeleteApiKeys200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/api-keys/{api_key_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getApiKeysById operation.
     * @callback module:api/APIKeysApi~getApiKeysByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetApiKeysById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get single API key by ID.     Returns masked API key for security (sk_****1234).
     * @param {String} companyId Unique identifier for the Company
     * @param {String} apiKeyId Unique identifier for the Api Key
     * @param {module:api/APIKeysApi~getApiKeysByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetApiKeysById200Response}
     */
    getApiKeysById(companyId, apiKeyId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getApiKeysById");
      }
      // verify the required parameter 'apiKeyId' is set
      if (apiKeyId === undefined || apiKeyId === null) {
        throw new Error("Missing the required parameter 'apiKeyId' when calling getApiKeysById");
      }

      let pathParams = {
        'company_id': companyId,
        'api_key_id': apiKeyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetApiKeysById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/api-keys/{api_key_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getApiKeysByIdApiKeysStats operation.
     * @callback module:api/APIKeysApi~getApiKeysByIdApiKeysStatsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetApiKeysById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get usage statistics for a specific API key.     Returns usage count, last used date, failed attempts, etc.
     * @param {String} companyId Unique identifier for the Company
     * @param {String} apiKeyId Unique identifier for the Api Key
     * @param {module:api/APIKeysApi~getApiKeysByIdApiKeysStatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetApiKeysById200Response}
     */
    getApiKeysByIdApiKeysStats(companyId, apiKeyId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getApiKeysByIdApiKeysStats");
      }
      // verify the required parameter 'apiKeyId' is set
      if (apiKeyId === undefined || apiKeyId === null) {
        throw new Error("Missing the required parameter 'apiKeyId' when calling getApiKeysByIdApiKeysStats");
      }

      let pathParams = {
        'company_id': companyId,
        'api_key_id': apiKeyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetApiKeysById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/api-keys/{api_key_id}/stats', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listApiKeys operation.
     * @callback module:api/APIKeysApi~listApiKeysCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListApiKeys200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all API keys for a company.     Returns masked API keys for security (sk_****1234).
     * @param {String} companyId Unique identifier for the Company
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] Page number for pagination
     * @param {Number} [limit = 20)] Number of items per page
     * @param {String} [sortBy] Field to sort by
     * @param {module:model/String} [sortOrder = 'desc')] Sort order (ascending or descending)
     * @param {String} [search] Search term to filter results
     * @param {module:api/APIKeysApi~listApiKeysCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ListApiKeys200Response}
     */
    listApiKeys(companyId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling listApiKeys");
      }

      let pathParams = {
        'company_id': companyId
      };
      let queryParams = {
        'page': opts['page'],
        'limit': opts['limit'],
        'sort_by': opts['sortBy'],
        'sort_order': opts['sortOrder'],
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListApiKeys200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/api-keys', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateApiKeys operation.
     * @callback module:api/APIKeysApi~updateApiKeysCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UpdateApiKeys200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an existing API key by ID.     Can update metadata like name, expiration, rate limits, etc.     Cannot update the actual key value (for security).
     * @param {String} companyId Unique identifier for the Company
     * @param {String} apiKeyId Unique identifier for the Api Key
     * @param {module:model/ApiKeysUpdate} apiKeysUpdate 
     * @param {module:api/APIKeysApi~updateApiKeysCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UpdateApiKeys200Response}
     */
    updateApiKeys(companyId, apiKeyId, apiKeysUpdate, callback) {
      let postBody = apiKeysUpdate;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling updateApiKeys");
      }
      // verify the required parameter 'apiKeyId' is set
      if (apiKeyId === undefined || apiKeyId === null) {
        throw new Error("Missing the required parameter 'apiKeyId' when calling updateApiKeys");
      }
      // verify the required parameter 'apiKeysUpdate' is set
      if (apiKeysUpdate === undefined || apiKeysUpdate === null) {
        throw new Error("Missing the required parameter 'apiKeysUpdate' when calling updateApiKeys");
      }

      let pathParams = {
        'company_id': companyId,
        'api_key_id': apiKeyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UpdateApiKeys200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/api-keys/{api_key_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
