/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetCloudProvidersById200Response from '../model/GetCloudProvidersById200Response';
import InlineObject1 from '../model/InlineObject1';
import InlineObject2 from '../model/InlineObject2';
import InlineObject3 from '../model/InlineObject3';
import InlineObject6 from '../model/InlineObject6';
import InlineObject7 from '../model/InlineObject7';
import ListCloudProviders200Response from '../model/ListCloudProviders200Response';

/**
* CloudProviders service.
* @module api/CloudProvidersApi
* @version 1.25.0
*/
export default class CloudProvidersApi {

    /**
    * Constructs a new CloudProvidersApi. 
    * @alias module:api/CloudProvidersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCloudProvidersById operation.
     * @callback module:api/CloudProvidersApi~getCloudProvidersByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetCloudProvidersById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get single cloud provider by ID
     * @param {String} providerId Unique identifier for the Provider
     * @param {module:api/CloudProvidersApi~getCloudProvidersByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetCloudProvidersById200Response}
     */
    getCloudProvidersById(providerId, callback) {
      let postBody = null;
      // verify the required parameter 'providerId' is set
      if (providerId === undefined || providerId === null) {
        throw new Error("Missing the required parameter 'providerId' when calling getCloudProvidersById");
      }

      let pathParams = {
        'provider_id': providerId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetCloudProvidersById200Response;
      return this.apiClient.callApi(
        '/cloud-providers/{provider_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listCloudProviders operation.
     * @callback module:api/CloudProvidersApi~listCloudProvidersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListCloudProviders200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of all cloud providers
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] Page number for pagination
     * @param {Number} [limit = 20)] Number of items per page
     * @param {String} [sortBy] Field to sort by
     * @param {module:model/String} [sortOrder = 'desc')] Sort order (ascending or descending)
     * @param {String} [search] Search term to filter results
     * @param {module:api/CloudProvidersApi~listCloudProvidersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ListCloudProviders200Response}
     */
    listCloudProviders(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'limit': opts['limit'],
        'sort_by': opts['sortBy'],
        'sort_order': opts['sortOrder'],
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListCloudProviders200Response;
      return this.apiClient.callApi(
        '/cloud-providers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
