/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateFavorites200Response from '../model/CreateFavorites200Response';
import DeleteFavorites200Response from '../model/DeleteFavorites200Response';
import FavoritesInput from '../model/FavoritesInput';
import FavoritesUpdate from '../model/FavoritesUpdate';
import GetFavoritesById200Response from '../model/GetFavoritesById200Response';
import InlineObject from '../model/InlineObject';
import InlineObject1 from '../model/InlineObject1';
import InlineObject2 from '../model/InlineObject2';
import InlineObject3 from '../model/InlineObject3';
import InlineObject4 from '../model/InlineObject4';
import InlineObject5 from '../model/InlineObject5';
import InlineObject6 from '../model/InlineObject6';
import InlineObject7 from '../model/InlineObject7';
import UpdateFavorites200Response from '../model/UpdateFavorites200Response';

/**
* Favorites service.
* @module api/FavoritesApi
* @version 1.25.0
*/
export default class FavoritesApi {

    /**
    * Constructs a new FavoritesApi. 
    * @alias module:api/FavoritesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createFavorites operation.
     * @callback module:api/FavoritesApi~createFavoritesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateFavorites200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * POST /companies/{company_id}/users/{user_id}/favorites
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {module:model/FavoritesInput} favoritesInput 
     * @param {module:api/FavoritesApi~createFavoritesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateFavorites200Response}
     */
    createFavorites(companyId, userId, favoritesInput, callback) {
      let postBody = favoritesInput;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling createFavorites");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling createFavorites");
      }
      // verify the required parameter 'favoritesInput' is set
      if (favoritesInput === undefined || favoritesInput === null) {
        throw new Error("Missing the required parameter 'favoritesInput' when calling createFavorites");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateFavorites200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/favorites', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteFavorites operation.
     * @callback module:api/FavoritesApi~deleteFavoritesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeleteFavorites200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete single favorite by ID (unfavorite an asset)
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} favoriteId Unique identifier for the Favorite
     * @param {module:api/FavoritesApi~deleteFavoritesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeleteFavorites200Response}
     */
    deleteFavorites(companyId, userId, favoriteId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling deleteFavorites");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling deleteFavorites");
      }
      // verify the required parameter 'favoriteId' is set
      if (favoriteId === undefined || favoriteId === null) {
        throw new Error("Missing the required parameter 'favoriteId' when calling deleteFavorites");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'favorite_id': favoriteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DeleteFavorites200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/favorites/{favorite_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFavoritesById operation.
     * @callback module:api/FavoritesApi~getFavoritesByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetFavoritesById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of all favorites for a specific user
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {module:api/FavoritesApi~getFavoritesByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetFavoritesById200Response}
     */
    getFavoritesById(companyId, userId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getFavoritesById");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getFavoritesById");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetFavoritesById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/favorites', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFavoritesByIdUsers operation.
     * @callback module:api/FavoritesApi~getFavoritesByIdUsersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetFavoritesById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get single favorite by ID
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} favoriteId Unique identifier for the Favorite
     * @param {module:api/FavoritesApi~getFavoritesByIdUsersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetFavoritesById200Response}
     */
    getFavoritesByIdUsers(companyId, userId, favoriteId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getFavoritesByIdUsers");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getFavoritesByIdUsers");
      }
      // verify the required parameter 'favoriteId' is set
      if (favoriteId === undefined || favoriteId === null) {
        throw new Error("Missing the required parameter 'favoriteId' when calling getFavoritesByIdUsers");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'favorite_id': favoriteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetFavoritesById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/favorites/{favorite_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFavoritesByIdUsersCategory operation.
     * @callback module:api/FavoritesApi~getFavoritesByIdUsersCategoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetFavoritesById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all favorites for the specified user in a specific category
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} category Parameter for category
     * @param {module:api/FavoritesApi~getFavoritesByIdUsersCategoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetFavoritesById200Response}
     */
    getFavoritesByIdUsersCategory(companyId, userId, category, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getFavoritesByIdUsersCategory");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getFavoritesByIdUsersCategory");
      }
      // verify the required parameter 'category' is set
      if (category === undefined || category === null) {
        throw new Error("Missing the required parameter 'category' when calling getFavoritesByIdUsersCategory");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'category': category
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetFavoritesById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/favorites/category/{category}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFavoritesByIdUsersCheck operation.
     * @callback module:api/FavoritesApi~getFavoritesByIdUsersCheckCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetFavoritesById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check if the specified user has favorited a specific asset
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} assetId Unique identifier for the Asset
     * @param {module:api/FavoritesApi~getFavoritesByIdUsersCheckCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetFavoritesById200Response}
     */
    getFavoritesByIdUsersCheck(companyId, userId, assetId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getFavoritesByIdUsersCheck");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getFavoritesByIdUsersCheck");
      }
      // verify the required parameter 'assetId' is set
      if (assetId === undefined || assetId === null) {
        throw new Error("Missing the required parameter 'assetId' when calling getFavoritesByIdUsersCheck");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'asset_id': assetId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetFavoritesById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/favorites/check/{asset_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFavoritesByIdUsersUncategorized operation.
     * @callback module:api/FavoritesApi~getFavoritesByIdUsersUncategorizedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetFavoritesById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all favorites for the specified user that don't have a category
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {module:api/FavoritesApi~getFavoritesByIdUsersUncategorizedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetFavoritesById200Response}
     */
    getFavoritesByIdUsersUncategorized(companyId, userId, callback) {
      let postBody = null;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getFavoritesByIdUsersUncategorized");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getFavoritesByIdUsersUncategorized");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetFavoritesById200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/favorites/uncategorized', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateFavorites operation.
     * @callback module:api/FavoritesApi~updateFavoritesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UpdateFavorites200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an existing favorite by ID
     * @param {String} companyId Unique identifier for the Company
     * @param {String} userId Unique identifier for the User
     * @param {String} favoriteId Unique identifier for the Favorite
     * @param {module:model/FavoritesUpdate} favoritesUpdate 
     * @param {module:api/FavoritesApi~updateFavoritesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UpdateFavorites200Response}
     */
    updateFavorites(companyId, userId, favoriteId, favoritesUpdate, callback) {
      let postBody = favoritesUpdate;
      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling updateFavorites");
      }
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling updateFavorites");
      }
      // verify the required parameter 'favoriteId' is set
      if (favoriteId === undefined || favoriteId === null) {
        throw new Error("Missing the required parameter 'favoriteId' when calling updateFavorites");
      }
      // verify the required parameter 'favoritesUpdate' is set
      if (favoritesUpdate === undefined || favoritesUpdate === null) {
        throw new Error("Missing the required parameter 'favoritesUpdate' when calling updateFavorites");
      }

      let pathParams = {
        'company_id': companyId,
        'user_id': userId,
        'favorite_id': favoriteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UpdateFavorites200Response;
      return this.apiClient.callApi(
        '/companies/{company_id}/users/{user_id}/favorites/{favorite_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
