/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetIndustriesById200Response from '../model/GetIndustriesById200Response';
import InlineObject1 from '../model/InlineObject1';
import InlineObject2 from '../model/InlineObject2';
import InlineObject3 from '../model/InlineObject3';
import InlineObject6 from '../model/InlineObject6';
import InlineObject7 from '../model/InlineObject7';
import ListIndustries200Response from '../model/ListIndustries200Response';

/**
* Industries service.
* @module api/IndustriesApi
* @version 1.25.0
*/
export default class IndustriesApi {

    /**
    * Constructs a new IndustriesApi. 
    * @alias module:api/IndustriesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getIndustriesById operation.
     * @callback module:api/IndustriesApi~getIndustriesByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetIndustriesById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get single industry by ID
     * @param {String} industryId Unique identifier for the Industry
     * @param {module:api/IndustriesApi~getIndustriesByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetIndustriesById200Response}
     */
    getIndustriesById(industryId, callback) {
      let postBody = null;
      // verify the required parameter 'industryId' is set
      if (industryId === undefined || industryId === null) {
        throw new Error("Missing the required parameter 'industryId' when calling getIndustriesById");
      }

      let pathParams = {
        'industry_id': industryId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetIndustriesById200Response;
      return this.apiClient.callApi(
        '/industries/{industry_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listIndustries operation.
     * @callback module:api/IndustriesApi~listIndustriesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListIndustries200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of all industries
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] Page number for pagination
     * @param {Number} [limit = 20)] Number of items per page
     * @param {String} [sortBy] Field to sort by
     * @param {module:model/String} [sortOrder = 'desc')] Sort order (ascending or descending)
     * @param {String} [search] Search term to filter results
     * @param {module:api/IndustriesApi~listIndustriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ListIndustries200Response}
     */
    listIndustries(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'limit': opts['limit'],
        'sort_by': opts['sortBy'],
        'sort_order': opts['sortOrder'],
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListIndustries200Response;
      return this.apiClient.callApi(
        '/industries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listIndustriesActive operation.
     * @callback module:api/IndustriesApi~listIndustriesActiveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListIndustries200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of industries that have active marketplace products
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] Page number for pagination
     * @param {Number} [limit = 20)] Number of items per page
     * @param {String} [sortBy] Field to sort by
     * @param {module:model/String} [sortOrder = 'desc')] Sort order (ascending or descending)
     * @param {String} [search] Search term to filter results
     * @param {module:api/IndustriesApi~listIndustriesActiveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ListIndustries200Response}
     */
    listIndustriesActive(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'limit': opts['limit'],
        'sort_by': opts['sortBy'],
        'sort_order': opts['sortOrder'],
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListIndustries200Response;
      return this.apiClient.callApi(
        '/industries/active', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
