/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetStorageEnginesById200Response from '../model/GetStorageEnginesById200Response';
import InlineObject1 from '../model/InlineObject1';
import InlineObject2 from '../model/InlineObject2';
import InlineObject3 from '../model/InlineObject3';
import InlineObject6 from '../model/InlineObject6';
import InlineObject7 from '../model/InlineObject7';
import ListStorageEngines200Response from '../model/ListStorageEngines200Response';

/**
* StorageEngines service.
* @module api/StorageEnginesApi
* @version 1.25.0
*/
export default class StorageEnginesApi {

    /**
    * Constructs a new StorageEnginesApi. 
    * @alias module:api/StorageEnginesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getStorageEnginesById operation.
     * @callback module:api/StorageEnginesApi~getStorageEnginesByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetStorageEnginesById200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get single storage engine by ID
     * @param {String} providerId Unique identifier for the Provider
     * @param {String} engineId Unique identifier for the Engine
     * @param {module:api/StorageEnginesApi~getStorageEnginesByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetStorageEnginesById200Response}
     */
    getStorageEnginesById(providerId, engineId, callback) {
      let postBody = null;
      // verify the required parameter 'providerId' is set
      if (providerId === undefined || providerId === null) {
        throw new Error("Missing the required parameter 'providerId' when calling getStorageEnginesById");
      }
      // verify the required parameter 'engineId' is set
      if (engineId === undefined || engineId === null) {
        throw new Error("Missing the required parameter 'engineId' when calling getStorageEnginesById");
      }

      let pathParams = {
        'provider_id': providerId,
        'engine_id': engineId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetStorageEnginesById200Response;
      return this.apiClient.callApi(
        '/cloud-providers/{provider_id}/storage-engines/{engine_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listStorageEngines operation.
     * @callback module:api/StorageEnginesApi~listStorageEnginesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ListStorageEngines200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of all storage engines
     * @param {String} providerId Unique identifier for the Provider
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] Page number for pagination
     * @param {Number} [limit = 20)] Number of items per page
     * @param {String} [sortBy] Field to sort by
     * @param {module:model/String} [sortOrder = 'desc')] Sort order (ascending or descending)
     * @param {String} [search] Search term to filter results
     * @param {module:api/StorageEnginesApi~listStorageEnginesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ListStorageEngines200Response}
     */
    listStorageEngines(providerId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'providerId' is set
      if (providerId === undefined || providerId === null) {
        throw new Error("Missing the required parameter 'providerId' when calling listStorageEngines");
      }

      let pathParams = {
        'provider_id': providerId
      };
      let queryParams = {
        'page': opts['page'],
        'limit': opts['limit'],
        'sort_by': opts['sortBy'],
        'sort_order': opts['sortOrder'],
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListStorageEngines200Response;
      return this.apiClient.callApi(
        '/cloud-providers/{provider_id}/storage-engines', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
