/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiSdk);
  }
}(this, function(expect, SparteraApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiSdk.ApiKeys();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiKeys', function() {
    it('should create an instance of ApiKeys', function() {
      // uncomment below and update the code to test ApiKeys
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be.a(SparteraApiSdk.ApiKeys);
    });

    it('should have the property dateCreated (base name: "date_created")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "last_updated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property apiKeyId (base name: "api_key_id")', function() {
      // uncomment below and update the code to test the property apiKeyId
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "company_id")', function() {
      // uncomment below and update the code to test the property companyId
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property roleId (base name: "role_id")', function() {
      // uncomment below and update the code to test the property roleId
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property keyType (base name: "key_type")', function() {
      // uncomment below and update the code to test the property keyType
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property isSystemGenerated (base name: "is_system_generated")', function() {
      // uncomment below and update the code to test the property isSystemGenerated
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property mcpDeploymentId (base name: "mcp_deployment_id")', function() {
      // uncomment below and update the code to test the property mcpDeploymentId
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property endpointId (base name: "endpoint_id")', function() {
      // uncomment below and update the code to test the property endpointId
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

    it('should have the property expirationDateUtc (base name: "expiration_date_utc")', function() {
      // uncomment below and update the code to test the property expirationDateUtc
      //var instance = new SparteraApiSdk.ApiKeys();
      //expect(instance).to.be();
    });

  });

}));
