/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiSdk);
  }
}(this, function(expect, SparteraApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiSdk.AssetsUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssetsUpdate', function() {
    it('should create an instance of AssetsUpdate', function() {
      // uncomment below and update the code to test AssetsUpdate
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be.a(SparteraApiSdk.AssetsUpdate);
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "company_id")', function() {
      // uncomment below and update the code to test the property companyId
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property connectionId (base name: "connection_id")', function() {
      // uncomment below and update the code to test the property connectionId
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property industryId (base name: "industry_id")', function() {
      // uncomment below and update the code to test the property industryId
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property aucId (base name: "auc_id")', function() {
      // uncomment below and update the code to test the property aucId
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property functionId (base name: "function_id")', function() {
      // uncomment below and update the code to test the property functionId
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property approvalStatus (base name: "approval_status")', function() {
      // uncomment below and update the code to test the property approvalStatus
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property approvedByUserId (base name: "approved_by_user_id")', function() {
      // uncomment below and update the code to test the property approvedByUserId
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property approvedAt (base name: "approved_at")', function() {
      // uncomment below and update the code to test the property approvedAt
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property slug (base name: "slug")', function() {
      // uncomment below and update the code to test the property slug
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property detailedDescription (base name: "detailed_description")', function() {
      // uncomment below and update the code to test the property detailedDescription
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property assetType (base name: "asset_type")', function() {
      // uncomment below and update the code to test the property assetType
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property assetSchema (base name: "asset_schema")', function() {
      // uncomment below and update the code to test the property assetSchema
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property shortCode (base name: "short_code")', function() {
      // uncomment below and update the code to test the property shortCode
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property restrictedDomains (base name: "restricted_domains")', function() {
      // uncomment below and update the code to test the property restrictedDomains
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property sqlLogic (base name: "sql_logic")', function() {
      // uncomment below and update the code to test the property sqlLogic
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property sourceSchemaName (base name: "source_schema_name")', function() {
      // uncomment below and update the code to test the property sourceSchemaName
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property sourceTableName (base name: "source_table_name")', function() {
      // uncomment below and update the code to test the property sourceTableName
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property sellInMarketplace (base name: "sell_in_marketplace")', function() {
      // uncomment below and update the code to test the property sellInMarketplace
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property requireCustomization (base name: "require_customization")', function() {
      // uncomment below and update the code to test the property requireCustomization
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizChartLibrary (base name: "viz_chart_library")', function() {
      // uncomment below and update the code to test the property vizChartLibrary
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizChartType (base name: "viz_chart_type")', function() {
      // uncomment below and update the code to test the property vizChartType
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizDepVarColName (base name: "viz_dep_var_col_name")', function() {
      // uncomment below and update the code to test the property vizDepVarColName
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizIndepVarColName (base name: "viz_indep_var_col_name")', function() {
      // uncomment below and update the code to test the property vizIndepVarColName
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizSizeColName (base name: "viz_size_col_name")', function() {
      // uncomment below and update the code to test the property vizSizeColName
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizColorColName (base name: "viz_color_col_name")', function() {
      // uncomment below and update the code to test the property vizColorColName
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizDataAggregation (base name: "viz_data_aggregation")', function() {
      // uncomment below and update the code to test the property vizDataAggregation
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizSortDirection (base name: "viz_sort_direction")', function() {
      // uncomment below and update the code to test the property vizSortDirection
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizDataLimit (base name: "viz_data_limit")', function() {
      // uncomment below and update the code to test the property vizDataLimit
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizColorScheme (base name: "viz_color_scheme")', function() {
      // uncomment below and update the code to test the property vizColorScheme
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizShowLegend (base name: "viz_show_legend")', function() {
      // uncomment below and update the code to test the property vizShowLegend
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizShowGrid (base name: "viz_show_grid")', function() {
      // uncomment below and update the code to test the property vizShowGrid
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizShowTrendline (base name: "viz_show_trendline")', function() {
      // uncomment below and update the code to test the property vizShowTrendline
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizLineSmoothing (base name: "viz_line_smoothing")', function() {
      // uncomment below and update the code to test the property vizLineSmoothing
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizBarStacked (base name: "viz_bar_stacked")', function() {
      // uncomment below and update the code to test the property vizBarStacked
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property vizFilterDirection (base name: "viz_filter_direction")', function() {
      // uncomment below and update the code to test the property vizFilterDirection
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property allowParams (base name: "allow_params")', function() {
      // uncomment below and update the code to test the property allowParams
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property acceptTerms (base name: "accept_terms")', function() {
      // uncomment below and update the code to test the property acceptTerms
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property cached (base name: "cached")', function() {
      // uncomment below and update the code to test the property cached
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property schedule (base name: "schedule")', function() {
      // uncomment below and update the code to test the property schedule
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property nextRun (base name: "next_run")', function() {
      // uncomment below and update the code to test the property nextRun
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property dataTimePeriodStart (base name: "data_time_period_start")', function() {
      // uncomment below and update the code to test the property dataTimePeriodStart
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property dataTimePeriodEnd (base name: "data_time_period_end")', function() {
      // uncomment below and update the code to test the property dataTimePeriodEnd
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property geographicCoverageType (base name: "geographic_coverage_type")', function() {
      // uncomment below and update the code to test the property geographicCoverageType
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property geographicCoverageDetails (base name: "geographic_coverage_details")', function() {
      // uncomment below and update the code to test the property geographicCoverageDetails
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property dataSourceRefreshFrequency (base name: "data_source_refresh_frequency")', function() {
      // uncomment below and update the code to test the property dataSourceRefreshFrequency
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property dataSourceLastRefreshed (base name: "data_source_last_refreshed")', function() {
      // uncomment below and update the code to test the property dataSourceLastRefreshed
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property rateLimitNumber (base name: "rate_limit_number")', function() {
      // uncomment below and update the code to test the property rateLimitNumber
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property rateLimitPeriod (base name: "rate_limit_period")', function() {
      // uncomment below and update the code to test the property rateLimitPeriod
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

    it('should have the property rateLimitGranularity (base name: "rate_limit_granularity")', function() {
      // uncomment below and update the code to test the property rateLimitGranularity
      //var instance = new SparteraApiSdk.AssetsUpdate();
      //expect(instance).to.be();
    });

  });

}));
