/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.24.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiDocumentation);
  }
}(this, function(expect, SparteraApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiDocumentation.CloudProviders();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CloudProviders', function() {
    it('should create an instance of CloudProviders', function() {
      // uncomment below and update the code to test CloudProviders
      //var instance = new SparteraApiDocumentation.CloudProviders();
      //expect(instance).to.be.a(SparteraApiDocumentation.CloudProviders);
    });

    it('should have the property dateCreated (base name: "date_created")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new SparteraApiDocumentation.CloudProviders();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "last_updated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instance = new SparteraApiDocumentation.CloudProviders();
      //expect(instance).to.be();
    });

    it('should have the property providerId (base name: "provider_id")', function() {
      // uncomment below and update the code to test the property providerId
      //var instance = new SparteraApiDocumentation.CloudProviders();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SparteraApiDocumentation.CloudProviders();
      //expect(instance).to.be();
    });

    it('should have the property parentCompany (base name: "parent_company")', function() {
      // uncomment below and update the code to test the property parentCompany
      //var instance = new SparteraApiDocumentation.CloudProviders();
      //expect(instance).to.be();
    });

    it('should have the property marketingHomepageUrl (base name: "marketing_homepage_url")', function() {
      // uncomment below and update the code to test the property marketingHomepageUrl
      //var instance = new SparteraApiDocumentation.CloudProviders();
      //expect(instance).to.be();
    });

  });

}));
