/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiDocumentation);
  }
}(this, function(expect, SparteraApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiDocumentation.CompaniesCompanyIdAssetsAssetIdPatch200ResponseData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompaniesCompanyIdAssetsAssetIdPatch200ResponseData', function() {
    it('should create an instance of CompaniesCompanyIdAssetsAssetIdPatch200ResponseData', function() {
      // uncomment below and update the code to test CompaniesCompanyIdAssetsAssetIdPatch200ResponseData
      //var instance = new SparteraApiDocumentation.CompaniesCompanyIdAssetsAssetIdPatch200ResponseData();
      //expect(instance).to.be.a(SparteraApiDocumentation.CompaniesCompanyIdAssetsAssetIdPatch200ResponseData);
    });

    it('should have the property assetId (base name: "asset_id")', function() {
      // uncomment below and update the code to test the property assetId
      //var instance = new SparteraApiDocumentation.CompaniesCompanyIdAssetsAssetIdPatch200ResponseData();
      //expect(instance).to.be();
    });

  });

}));
