/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiDocumentation);
  }
}(this, function(expect, SparteraApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiDocumentation.Company();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Company', function() {
    it('should create an instance of Company', function() {
      // uncomment below and update the code to test Company
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be.a(SparteraApiDocumentation.Company);
    });

    it('should have the property companyId (base name: "company_id")', function() {
      // uncomment below and update the code to test the property companyId
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property industryId (base name: "industry_id")', function() {
      // uncomment below and update the code to test the property industryId
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property countryId (base name: "country_id")', function() {
      // uncomment below and update the code to test the property countryId
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "company_name")', function() {
      // uncomment below and update the code to test the property companyName
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property companyDescription (base name: "company_description")', function() {
      // uncomment below and update the code to test the property companyDescription
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property companyHandle (base name: "company_handle")', function() {
      // uncomment below and update the code to test the property companyHandle
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property companyDomain (base name: "company_domain")', function() {
      // uncomment below and update the code to test the property companyDomain
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property creditsBalance (base name: "credits_balance")', function() {
      // uncomment below and update the code to test the property creditsBalance
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property acceptedEula (base name: "accepted_eula")', function() {
      // uncomment below and update the code to test the property acceptedEula
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property stripeAccountId (base name: "stripe_account_id")', function() {
      // uncomment below and update the code to test the property stripeAccountId
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property stripeAccountStatus (base name: "stripe_account_status")', function() {
      // uncomment below and update the code to test the property stripeAccountStatus
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "date_created")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "last_updated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new SparteraApiDocumentation.Company();
      //expect(instance).to.be();
    });

  });

}));
