/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.24.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiDocumentation);
  }
}(this, function(expect, SparteraApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiDocumentation.ConnectionsInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConnectionsInput', function() {
    it('should create an instance of ConnectionsInput', function() {
      // uncomment below and update the code to test ConnectionsInput
      //var instance = new SparteraApiDocumentation.ConnectionsInput();
      //expect(instance).to.be.a(SparteraApiDocumentation.ConnectionsInput);
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new SparteraApiDocumentation.ConnectionsInput();
      //expect(instance).to.be();
    });

    it('should have the property engineId (base name: "engine_id")', function() {
      // uncomment below and update the code to test the property engineId
      //var instance = new SparteraApiDocumentation.ConnectionsInput();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "company_id")', function() {
      // uncomment below and update the code to test the property companyId
      //var instance = new SparteraApiDocumentation.ConnectionsInput();
      //expect(instance).to.be();
    });

    it('should have the property credentialType (base name: "credential_type")', function() {
      // uncomment below and update the code to test the property credentialType
      //var instance = new SparteraApiDocumentation.ConnectionsInput();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SparteraApiDocumentation.ConnectionsInput();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new SparteraApiDocumentation.ConnectionsInput();
      //expect(instance).to.be();
    });

    it('should have the property providerDomain (base name: "provider_domain")', function() {
      // uncomment below and update the code to test the property providerDomain
      //var instance = new SparteraApiDocumentation.ConnectionsInput();
      //expect(instance).to.be();
    });

    it('should have the property verifiedUsageAbility (base name: "verified_usage_ability")', function() {
      // uncomment below and update the code to test the property verifiedUsageAbility
      //var instance = new SparteraApiDocumentation.ConnectionsInput();
      //expect(instance).to.be();
    });

  });

}));
