/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiSdk);
  }
}(this, function(expect, SparteraApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiSdk.PostgenIntegrations();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostgenIntegrations', function() {
    it('should create an instance of PostgenIntegrations', function() {
      // uncomment below and update the code to test PostgenIntegrations
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be.a(SparteraApiSdk.PostgenIntegrations);
    });

    it('should have the property dateCreated (base name: "date_created")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "last_updated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

    it('should have the property integrationId (base name: "integration_id")', function() {
      // uncomment below and update the code to test the property integrationId
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "company_id")', function() {
      // uncomment below and update the code to test the property companyId
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

    it('should have the property platform (base name: "platform")', function() {
      // uncomment below and update the code to test the property platform
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

    it('should have the property platformName (base name: "platform_name")', function() {
      // uncomment below and update the code to test the property platformName
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

    it('should have the property credentialsSecretName (base name: "credentials_secret_name")', function() {
      // uncomment below and update the code to test the property credentialsSecretName
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "is_active")', function() {
      // uncomment below and update the code to test the property isActive
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

    it('should have the property lastUsedAt (base name: "last_used_at")', function() {
      // uncomment below and update the code to test the property lastUsedAt
      //var instance = new SparteraApiSdk.PostgenIntegrations();
      //expect(instance).to.be();
    });

  });

}));
