/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Alerts from './model/Alerts';
import AlertsInput from './model/AlertsInput';
import AlertsUpdate from './model/AlertsUpdate';
import ApiKeys from './model/ApiKeys';
import ApiKeysInput from './model/ApiKeysInput';
import ApiKeysUpdate from './model/ApiKeysUpdate';
import AssetPriceHistory from './model/AssetPriceHistory';
import AssetPriceHistoryInput from './model/AssetPriceHistoryInput';
import AssetPriceHistoryUpdate from './model/AssetPriceHistoryUpdate';
import AssetUsecases from './model/AssetUsecases';
import Assets from './model/Assets';
import AssetsInput from './model/AssetsInput';
import AssetsUpdate from './model/AssetsUpdate';
import CloudProviders from './model/CloudProviders';
import CloudProvidersInput from './model/CloudProvidersInput';
import CloudProvidersUpdate from './model/CloudProvidersUpdate';
import Companies from './model/Companies';
import CompaniesInput from './model/CompaniesInput';
import CompaniesUpdate from './model/CompaniesUpdate';
import Connections from './model/Connections';
import ConnectionsInput from './model/ConnectionsInput';
import ConnectionsUpdate from './model/ConnectionsUpdate';
import CreateAlerts200Response from './model/CreateAlerts200Response';
import CreateAlerts200ResponseData from './model/CreateAlerts200ResponseData';
import CreateApiKeys200Response from './model/CreateApiKeys200Response';
import CreateApiKeys200ResponseData from './model/CreateApiKeys200ResponseData';
import CreateAssetPriceHistory200Response from './model/CreateAssetPriceHistory200Response';
import CreateAssetPriceHistory200ResponseData from './model/CreateAssetPriceHistory200ResponseData';
import CreateAssetsAnalyze200Response from './model/CreateAssetsAnalyze200Response';
import CreateAssetsAnalyze200ResponseData from './model/CreateAssetsAnalyze200ResponseData';
import CreateConnections200Response from './model/CreateConnections200Response';
import CreateConnections200ResponseData from './model/CreateConnections200ResponseData';
import CreateEndpoints200Response from './model/CreateEndpoints200Response';
import CreateEndpoints200ResponseData from './model/CreateEndpoints200ResponseData';
import CreateFavorites200Response from './model/CreateFavorites200Response';
import CreateFavorites200ResponseData from './model/CreateFavorites200ResponseData';
import CreatePostgenIntegrations200Response from './model/CreatePostgenIntegrations200Response';
import CreatePostgenIntegrations200ResponseData from './model/CreatePostgenIntegrations200ResponseData';
import CreatePosts200Response from './model/CreatePosts200Response';
import CreatePosts200ResponseData from './model/CreatePosts200ResponseData';
import CreateUsers200Response from './model/CreateUsers200Response';
import CreateUsers200ResponseData from './model/CreateUsers200ResponseData';
import DeleteAlerts200Response from './model/DeleteAlerts200Response';
import DeleteAlerts200ResponseData from './model/DeleteAlerts200ResponseData';
import DeleteApiKeys200Response from './model/DeleteApiKeys200Response';
import DeleteApiKeys200ResponseData from './model/DeleteApiKeys200ResponseData';
import DeleteAssetPriceHistory200Response from './model/DeleteAssetPriceHistory200Response';
import DeleteAssetPriceHistory200ResponseData from './model/DeleteAssetPriceHistory200ResponseData';
import DeleteAssets200Response from './model/DeleteAssets200Response';
import DeleteAssets200ResponseData from './model/DeleteAssets200ResponseData';
import DeleteConnections200Response from './model/DeleteConnections200Response';
import DeleteConnections200ResponseData from './model/DeleteConnections200ResponseData';
import DeleteEndpoints200Response from './model/DeleteEndpoints200Response';
import DeleteEndpoints200ResponseData from './model/DeleteEndpoints200ResponseData';
import DeleteFavorites200Response from './model/DeleteFavorites200Response';
import DeleteFavorites200ResponseData from './model/DeleteFavorites200ResponseData';
import DeletePostgenIntegrations200Response from './model/DeletePostgenIntegrations200Response';
import DeletePostgenIntegrations200ResponseData from './model/DeletePostgenIntegrations200ResponseData';
import DeletePosts200Response from './model/DeletePosts200Response';
import DeletePosts200ResponseData from './model/DeletePosts200ResponseData';
import DeleteUsers200Response from './model/DeleteUsers200Response';
import DeleteUsers200ResponseData from './model/DeleteUsers200ResponseData';
import Endpoints from './model/Endpoints';
import EndpointsInput from './model/EndpointsInput';
import EndpointsUpdate from './model/EndpointsUpdate';
import Error from './model/Error';
import Favorites from './model/Favorites';
import FavoritesInput from './model/FavoritesInput';
import FavoritesUpdate from './model/FavoritesUpdate';
import GetAlertsById200Response from './model/GetAlertsById200Response';
import GetApiKeysById200Response from './model/GetApiKeysById200Response';
import GetAssetPriceHistoryById200Response from './model/GetAssetPriceHistoryById200Response';
import GetAssetUsecasesById200Response from './model/GetAssetUsecasesById200Response';
import GetAssetsByIdAnalyze200Response from './model/GetAssetsByIdAnalyze200Response';
import GetCloudProvidersById200Response from './model/GetCloudProvidersById200Response';
import GetCompaniesById200Response from './model/GetCompaniesById200Response';
import GetConnectionsById200Response from './model/GetConnectionsById200Response';
import GetEndpointsByIdConnectionsDescribe200Response from './model/GetEndpointsByIdConnectionsDescribe200Response';
import GetFavoritesById200Response from './model/GetFavoritesById200Response';
import GetIndustriesById200Response from './model/GetIndustriesById200Response';
import GetJobFunctionsById200Response from './model/GetJobFunctionsById200Response';
import GetPostgenIntegrationsById200Response from './model/GetPostgenIntegrationsById200Response';
import GetPostsById200Response from './model/GetPostsById200Response';
import GetStorageEnginesById200Response from './model/GetStorageEnginesById200Response';
import GetUsersById200Response from './model/GetUsersById200Response';
import Industries from './model/Industries';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineObject2 from './model/InlineObject2';
import InlineObject3 from './model/InlineObject3';
import InlineObject4 from './model/InlineObject4';
import InlineObject5 from './model/InlineObject5';
import InlineObject6 from './model/InlineObject6';
import InlineObject7 from './model/InlineObject7';
import JobFunctions from './model/JobFunctions';
import JobFunctionsInput from './model/JobFunctionsInput';
import JobFunctionsUpdate from './model/JobFunctionsUpdate';
import ListApiKeys200Response from './model/ListApiKeys200Response';
import ListAssetUsecases200Response from './model/ListAssetUsecases200Response';
import ListAssets200Response from './model/ListAssets200Response';
import ListCloudProviders200Response from './model/ListCloudProviders200Response';
import ListCompaniesAnalyticsAssets200Response from './model/ListCompaniesAnalyticsAssets200Response';
import ListConnections200Response from './model/ListConnections200Response';
import ListEndpoints200Response from './model/ListEndpoints200Response';
import ListIndustries200Response from './model/ListIndustries200Response';
import ListJobFunctions200Response from './model/ListJobFunctions200Response';
import ListPostgenIntegrations200Response from './model/ListPostgenIntegrations200Response';
import ListPosts200Response from './model/ListPosts200Response';
import ListStorageEngines200Response from './model/ListStorageEngines200Response';
import ListUsers200Response from './model/ListUsers200Response';
import PostPublications from './model/PostPublications';
import PostPublicationsInput from './model/PostPublicationsInput';
import PostPublicationsUpdate from './model/PostPublicationsUpdate';
import PostgenIntegrations from './model/PostgenIntegrations';
import PostgenIntegrationsInput from './model/PostgenIntegrationsInput';
import PostgenIntegrationsUpdate from './model/PostgenIntegrationsUpdate';
import Posts from './model/Posts';
import PostsInput from './model/PostsInput';
import PostsUpdate from './model/PostsUpdate';
import StorageEngines from './model/StorageEngines';
import UpdateAlerts200Response from './model/UpdateAlerts200Response';
import UpdateAlerts200ResponseData from './model/UpdateAlerts200ResponseData';
import UpdateApiKeys200Response from './model/UpdateApiKeys200Response';
import UpdateApiKeys200ResponseData from './model/UpdateApiKeys200ResponseData';
import UpdateAssetPriceHistory200Response from './model/UpdateAssetPriceHistory200Response';
import UpdateAssetPriceHistory200ResponseData from './model/UpdateAssetPriceHistory200ResponseData';
import UpdateAssets200Response from './model/UpdateAssets200Response';
import UpdateAssets200ResponseData from './model/UpdateAssets200ResponseData';
import UpdateCompanies200Response from './model/UpdateCompanies200Response';
import UpdateCompanies200ResponseData from './model/UpdateCompanies200ResponseData';
import UpdateConnections200Response from './model/UpdateConnections200Response';
import UpdateConnections200ResponseData from './model/UpdateConnections200ResponseData';
import UpdateEndpoints200Response from './model/UpdateEndpoints200Response';
import UpdateEndpoints200ResponseData from './model/UpdateEndpoints200ResponseData';
import UpdateFavorites200Response from './model/UpdateFavorites200Response';
import UpdateFavorites200ResponseData from './model/UpdateFavorites200ResponseData';
import UpdatePostgenIntegrations200Response from './model/UpdatePostgenIntegrations200Response';
import UpdatePostgenIntegrations200ResponseData from './model/UpdatePostgenIntegrations200ResponseData';
import UpdatePosts200Response from './model/UpdatePosts200Response';
import UpdatePosts200ResponseData from './model/UpdatePosts200ResponseData';
import UpdateUsers200Response from './model/UpdateUsers200Response';
import UpdateUsers200ResponseData from './model/UpdateUsers200ResponseData';
import Users from './model/Users';
import UsersInput from './model/UsersInput';
import UsersUpdate from './model/UsersUpdate';
import APIKeysApi from './api/APIKeysApi';
import AlertsApi from './api/AlertsApi';
import AssetPriceHistoryApi from './api/AssetPriceHistoryApi';
import AssetUsecasesApi from './api/AssetUsecasesApi';
import AssetsApi from './api/AssetsApi';
import CloudProvidersApi from './api/CloudProvidersApi';
import CompaniesApi from './api/CompaniesApi';
import ConnectionsApi from './api/ConnectionsApi';
import EndpointsApi from './api/EndpointsApi';
import FavoritesApi from './api/FavoritesApi';
import IndustriesApi from './api/IndustriesApi';
import JobFunctionsApi from './api/JobFunctionsApi';
import PostgenIntegrationsApi from './api/PostgenIntegrationsApi';
import PostsApi from './api/PostsApi';
import StorageEnginesApi from './api/StorageEnginesApi';
import UsersApi from './api/UsersApi';


/**
* Auto-generated API documentation for REST services of the Spartera platform.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SparteraApiSdk = require('index'); // See note below*.
* var xxxSvc = new SparteraApiSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SparteraApiSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SparteraApiSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SparteraApiSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.25.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Alerts model constructor.
     * @property {module:model/Alerts}
     */
    Alerts,

    /**
     * The AlertsInput model constructor.
     * @property {module:model/AlertsInput}
     */
    AlertsInput,

    /**
     * The AlertsUpdate model constructor.
     * @property {module:model/AlertsUpdate}
     */
    AlertsUpdate,

    /**
     * The ApiKeys model constructor.
     * @property {module:model/ApiKeys}
     */
    ApiKeys,

    /**
     * The ApiKeysInput model constructor.
     * @property {module:model/ApiKeysInput}
     */
    ApiKeysInput,

    /**
     * The ApiKeysUpdate model constructor.
     * @property {module:model/ApiKeysUpdate}
     */
    ApiKeysUpdate,

    /**
     * The AssetPriceHistory model constructor.
     * @property {module:model/AssetPriceHistory}
     */
    AssetPriceHistory,

    /**
     * The AssetPriceHistoryInput model constructor.
     * @property {module:model/AssetPriceHistoryInput}
     */
    AssetPriceHistoryInput,

    /**
     * The AssetPriceHistoryUpdate model constructor.
     * @property {module:model/AssetPriceHistoryUpdate}
     */
    AssetPriceHistoryUpdate,

    /**
     * The AssetUsecases model constructor.
     * @property {module:model/AssetUsecases}
     */
    AssetUsecases,

    /**
     * The Assets model constructor.
     * @property {module:model/Assets}
     */
    Assets,

    /**
     * The AssetsInput model constructor.
     * @property {module:model/AssetsInput}
     */
    AssetsInput,

    /**
     * The AssetsUpdate model constructor.
     * @property {module:model/AssetsUpdate}
     */
    AssetsUpdate,

    /**
     * The CloudProviders model constructor.
     * @property {module:model/CloudProviders}
     */
    CloudProviders,

    /**
     * The CloudProvidersInput model constructor.
     * @property {module:model/CloudProvidersInput}
     */
    CloudProvidersInput,

    /**
     * The CloudProvidersUpdate model constructor.
     * @property {module:model/CloudProvidersUpdate}
     */
    CloudProvidersUpdate,

    /**
     * The Companies model constructor.
     * @property {module:model/Companies}
     */
    Companies,

    /**
     * The CompaniesInput model constructor.
     * @property {module:model/CompaniesInput}
     */
    CompaniesInput,

    /**
     * The CompaniesUpdate model constructor.
     * @property {module:model/CompaniesUpdate}
     */
    CompaniesUpdate,

    /**
     * The Connections model constructor.
     * @property {module:model/Connections}
     */
    Connections,

    /**
     * The ConnectionsInput model constructor.
     * @property {module:model/ConnectionsInput}
     */
    ConnectionsInput,

    /**
     * The ConnectionsUpdate model constructor.
     * @property {module:model/ConnectionsUpdate}
     */
    ConnectionsUpdate,

    /**
     * The CreateAlerts200Response model constructor.
     * @property {module:model/CreateAlerts200Response}
     */
    CreateAlerts200Response,

    /**
     * The CreateAlerts200ResponseData model constructor.
     * @property {module:model/CreateAlerts200ResponseData}
     */
    CreateAlerts200ResponseData,

    /**
     * The CreateApiKeys200Response model constructor.
     * @property {module:model/CreateApiKeys200Response}
     */
    CreateApiKeys200Response,

    /**
     * The CreateApiKeys200ResponseData model constructor.
     * @property {module:model/CreateApiKeys200ResponseData}
     */
    CreateApiKeys200ResponseData,

    /**
     * The CreateAssetPriceHistory200Response model constructor.
     * @property {module:model/CreateAssetPriceHistory200Response}
     */
    CreateAssetPriceHistory200Response,

    /**
     * The CreateAssetPriceHistory200ResponseData model constructor.
     * @property {module:model/CreateAssetPriceHistory200ResponseData}
     */
    CreateAssetPriceHistory200ResponseData,

    /**
     * The CreateAssetsAnalyze200Response model constructor.
     * @property {module:model/CreateAssetsAnalyze200Response}
     */
    CreateAssetsAnalyze200Response,

    /**
     * The CreateAssetsAnalyze200ResponseData model constructor.
     * @property {module:model/CreateAssetsAnalyze200ResponseData}
     */
    CreateAssetsAnalyze200ResponseData,

    /**
     * The CreateConnections200Response model constructor.
     * @property {module:model/CreateConnections200Response}
     */
    CreateConnections200Response,

    /**
     * The CreateConnections200ResponseData model constructor.
     * @property {module:model/CreateConnections200ResponseData}
     */
    CreateConnections200ResponseData,

    /**
     * The CreateEndpoints200Response model constructor.
     * @property {module:model/CreateEndpoints200Response}
     */
    CreateEndpoints200Response,

    /**
     * The CreateEndpoints200ResponseData model constructor.
     * @property {module:model/CreateEndpoints200ResponseData}
     */
    CreateEndpoints200ResponseData,

    /**
     * The CreateFavorites200Response model constructor.
     * @property {module:model/CreateFavorites200Response}
     */
    CreateFavorites200Response,

    /**
     * The CreateFavorites200ResponseData model constructor.
     * @property {module:model/CreateFavorites200ResponseData}
     */
    CreateFavorites200ResponseData,

    /**
     * The CreatePostgenIntegrations200Response model constructor.
     * @property {module:model/CreatePostgenIntegrations200Response}
     */
    CreatePostgenIntegrations200Response,

    /**
     * The CreatePostgenIntegrations200ResponseData model constructor.
     * @property {module:model/CreatePostgenIntegrations200ResponseData}
     */
    CreatePostgenIntegrations200ResponseData,

    /**
     * The CreatePosts200Response model constructor.
     * @property {module:model/CreatePosts200Response}
     */
    CreatePosts200Response,

    /**
     * The CreatePosts200ResponseData model constructor.
     * @property {module:model/CreatePosts200ResponseData}
     */
    CreatePosts200ResponseData,

    /**
     * The CreateUsers200Response model constructor.
     * @property {module:model/CreateUsers200Response}
     */
    CreateUsers200Response,

    /**
     * The CreateUsers200ResponseData model constructor.
     * @property {module:model/CreateUsers200ResponseData}
     */
    CreateUsers200ResponseData,

    /**
     * The DeleteAlerts200Response model constructor.
     * @property {module:model/DeleteAlerts200Response}
     */
    DeleteAlerts200Response,

    /**
     * The DeleteAlerts200ResponseData model constructor.
     * @property {module:model/DeleteAlerts200ResponseData}
     */
    DeleteAlerts200ResponseData,

    /**
     * The DeleteApiKeys200Response model constructor.
     * @property {module:model/DeleteApiKeys200Response}
     */
    DeleteApiKeys200Response,

    /**
     * The DeleteApiKeys200ResponseData model constructor.
     * @property {module:model/DeleteApiKeys200ResponseData}
     */
    DeleteApiKeys200ResponseData,

    /**
     * The DeleteAssetPriceHistory200Response model constructor.
     * @property {module:model/DeleteAssetPriceHistory200Response}
     */
    DeleteAssetPriceHistory200Response,

    /**
     * The DeleteAssetPriceHistory200ResponseData model constructor.
     * @property {module:model/DeleteAssetPriceHistory200ResponseData}
     */
    DeleteAssetPriceHistory200ResponseData,

    /**
     * The DeleteAssets200Response model constructor.
     * @property {module:model/DeleteAssets200Response}
     */
    DeleteAssets200Response,

    /**
     * The DeleteAssets200ResponseData model constructor.
     * @property {module:model/DeleteAssets200ResponseData}
     */
    DeleteAssets200ResponseData,

    /**
     * The DeleteConnections200Response model constructor.
     * @property {module:model/DeleteConnections200Response}
     */
    DeleteConnections200Response,

    /**
     * The DeleteConnections200ResponseData model constructor.
     * @property {module:model/DeleteConnections200ResponseData}
     */
    DeleteConnections200ResponseData,

    /**
     * The DeleteEndpoints200Response model constructor.
     * @property {module:model/DeleteEndpoints200Response}
     */
    DeleteEndpoints200Response,

    /**
     * The DeleteEndpoints200ResponseData model constructor.
     * @property {module:model/DeleteEndpoints200ResponseData}
     */
    DeleteEndpoints200ResponseData,

    /**
     * The DeleteFavorites200Response model constructor.
     * @property {module:model/DeleteFavorites200Response}
     */
    DeleteFavorites200Response,

    /**
     * The DeleteFavorites200ResponseData model constructor.
     * @property {module:model/DeleteFavorites200ResponseData}
     */
    DeleteFavorites200ResponseData,

    /**
     * The DeletePostgenIntegrations200Response model constructor.
     * @property {module:model/DeletePostgenIntegrations200Response}
     */
    DeletePostgenIntegrations200Response,

    /**
     * The DeletePostgenIntegrations200ResponseData model constructor.
     * @property {module:model/DeletePostgenIntegrations200ResponseData}
     */
    DeletePostgenIntegrations200ResponseData,

    /**
     * The DeletePosts200Response model constructor.
     * @property {module:model/DeletePosts200Response}
     */
    DeletePosts200Response,

    /**
     * The DeletePosts200ResponseData model constructor.
     * @property {module:model/DeletePosts200ResponseData}
     */
    DeletePosts200ResponseData,

    /**
     * The DeleteUsers200Response model constructor.
     * @property {module:model/DeleteUsers200Response}
     */
    DeleteUsers200Response,

    /**
     * The DeleteUsers200ResponseData model constructor.
     * @property {module:model/DeleteUsers200ResponseData}
     */
    DeleteUsers200ResponseData,

    /**
     * The Endpoints model constructor.
     * @property {module:model/Endpoints}
     */
    Endpoints,

    /**
     * The EndpointsInput model constructor.
     * @property {module:model/EndpointsInput}
     */
    EndpointsInput,

    /**
     * The EndpointsUpdate model constructor.
     * @property {module:model/EndpointsUpdate}
     */
    EndpointsUpdate,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Favorites model constructor.
     * @property {module:model/Favorites}
     */
    Favorites,

    /**
     * The FavoritesInput model constructor.
     * @property {module:model/FavoritesInput}
     */
    FavoritesInput,

    /**
     * The FavoritesUpdate model constructor.
     * @property {module:model/FavoritesUpdate}
     */
    FavoritesUpdate,

    /**
     * The GetAlertsById200Response model constructor.
     * @property {module:model/GetAlertsById200Response}
     */
    GetAlertsById200Response,

    /**
     * The GetApiKeysById200Response model constructor.
     * @property {module:model/GetApiKeysById200Response}
     */
    GetApiKeysById200Response,

    /**
     * The GetAssetPriceHistoryById200Response model constructor.
     * @property {module:model/GetAssetPriceHistoryById200Response}
     */
    GetAssetPriceHistoryById200Response,

    /**
     * The GetAssetUsecasesById200Response model constructor.
     * @property {module:model/GetAssetUsecasesById200Response}
     */
    GetAssetUsecasesById200Response,

    /**
     * The GetAssetsByIdAnalyze200Response model constructor.
     * @property {module:model/GetAssetsByIdAnalyze200Response}
     */
    GetAssetsByIdAnalyze200Response,

    /**
     * The GetCloudProvidersById200Response model constructor.
     * @property {module:model/GetCloudProvidersById200Response}
     */
    GetCloudProvidersById200Response,

    /**
     * The GetCompaniesById200Response model constructor.
     * @property {module:model/GetCompaniesById200Response}
     */
    GetCompaniesById200Response,

    /**
     * The GetConnectionsById200Response model constructor.
     * @property {module:model/GetConnectionsById200Response}
     */
    GetConnectionsById200Response,

    /**
     * The GetEndpointsByIdConnectionsDescribe200Response model constructor.
     * @property {module:model/GetEndpointsByIdConnectionsDescribe200Response}
     */
    GetEndpointsByIdConnectionsDescribe200Response,

    /**
     * The GetFavoritesById200Response model constructor.
     * @property {module:model/GetFavoritesById200Response}
     */
    GetFavoritesById200Response,

    /**
     * The GetIndustriesById200Response model constructor.
     * @property {module:model/GetIndustriesById200Response}
     */
    GetIndustriesById200Response,

    /**
     * The GetJobFunctionsById200Response model constructor.
     * @property {module:model/GetJobFunctionsById200Response}
     */
    GetJobFunctionsById200Response,

    /**
     * The GetPostgenIntegrationsById200Response model constructor.
     * @property {module:model/GetPostgenIntegrationsById200Response}
     */
    GetPostgenIntegrationsById200Response,

    /**
     * The GetPostsById200Response model constructor.
     * @property {module:model/GetPostsById200Response}
     */
    GetPostsById200Response,

    /**
     * The GetStorageEnginesById200Response model constructor.
     * @property {module:model/GetStorageEnginesById200Response}
     */
    GetStorageEnginesById200Response,

    /**
     * The GetUsersById200Response model constructor.
     * @property {module:model/GetUsersById200Response}
     */
    GetUsersById200Response,

    /**
     * The Industries model constructor.
     * @property {module:model/Industries}
     */
    Industries,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject2 model constructor.
     * @property {module:model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:model/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject4 model constructor.
     * @property {module:model/InlineObject4}
     */
    InlineObject4,

    /**
     * The InlineObject5 model constructor.
     * @property {module:model/InlineObject5}
     */
    InlineObject5,

    /**
     * The InlineObject6 model constructor.
     * @property {module:model/InlineObject6}
     */
    InlineObject6,

    /**
     * The InlineObject7 model constructor.
     * @property {module:model/InlineObject7}
     */
    InlineObject7,

    /**
     * The JobFunctions model constructor.
     * @property {module:model/JobFunctions}
     */
    JobFunctions,

    /**
     * The JobFunctionsInput model constructor.
     * @property {module:model/JobFunctionsInput}
     */
    JobFunctionsInput,

    /**
     * The JobFunctionsUpdate model constructor.
     * @property {module:model/JobFunctionsUpdate}
     */
    JobFunctionsUpdate,

    /**
     * The ListApiKeys200Response model constructor.
     * @property {module:model/ListApiKeys200Response}
     */
    ListApiKeys200Response,

    /**
     * The ListAssetUsecases200Response model constructor.
     * @property {module:model/ListAssetUsecases200Response}
     */
    ListAssetUsecases200Response,

    /**
     * The ListAssets200Response model constructor.
     * @property {module:model/ListAssets200Response}
     */
    ListAssets200Response,

    /**
     * The ListCloudProviders200Response model constructor.
     * @property {module:model/ListCloudProviders200Response}
     */
    ListCloudProviders200Response,

    /**
     * The ListCompaniesAnalyticsAssets200Response model constructor.
     * @property {module:model/ListCompaniesAnalyticsAssets200Response}
     */
    ListCompaniesAnalyticsAssets200Response,

    /**
     * The ListConnections200Response model constructor.
     * @property {module:model/ListConnections200Response}
     */
    ListConnections200Response,

    /**
     * The ListEndpoints200Response model constructor.
     * @property {module:model/ListEndpoints200Response}
     */
    ListEndpoints200Response,

    /**
     * The ListIndustries200Response model constructor.
     * @property {module:model/ListIndustries200Response}
     */
    ListIndustries200Response,

    /**
     * The ListJobFunctions200Response model constructor.
     * @property {module:model/ListJobFunctions200Response}
     */
    ListJobFunctions200Response,

    /**
     * The ListPostgenIntegrations200Response model constructor.
     * @property {module:model/ListPostgenIntegrations200Response}
     */
    ListPostgenIntegrations200Response,

    /**
     * The ListPosts200Response model constructor.
     * @property {module:model/ListPosts200Response}
     */
    ListPosts200Response,

    /**
     * The ListStorageEngines200Response model constructor.
     * @property {module:model/ListStorageEngines200Response}
     */
    ListStorageEngines200Response,

    /**
     * The ListUsers200Response model constructor.
     * @property {module:model/ListUsers200Response}
     */
    ListUsers200Response,

    /**
     * The PostPublications model constructor.
     * @property {module:model/PostPublications}
     */
    PostPublications,

    /**
     * The PostPublicationsInput model constructor.
     * @property {module:model/PostPublicationsInput}
     */
    PostPublicationsInput,

    /**
     * The PostPublicationsUpdate model constructor.
     * @property {module:model/PostPublicationsUpdate}
     */
    PostPublicationsUpdate,

    /**
     * The PostgenIntegrations model constructor.
     * @property {module:model/PostgenIntegrations}
     */
    PostgenIntegrations,

    /**
     * The PostgenIntegrationsInput model constructor.
     * @property {module:model/PostgenIntegrationsInput}
     */
    PostgenIntegrationsInput,

    /**
     * The PostgenIntegrationsUpdate model constructor.
     * @property {module:model/PostgenIntegrationsUpdate}
     */
    PostgenIntegrationsUpdate,

    /**
     * The Posts model constructor.
     * @property {module:model/Posts}
     */
    Posts,

    /**
     * The PostsInput model constructor.
     * @property {module:model/PostsInput}
     */
    PostsInput,

    /**
     * The PostsUpdate model constructor.
     * @property {module:model/PostsUpdate}
     */
    PostsUpdate,

    /**
     * The StorageEngines model constructor.
     * @property {module:model/StorageEngines}
     */
    StorageEngines,

    /**
     * The UpdateAlerts200Response model constructor.
     * @property {module:model/UpdateAlerts200Response}
     */
    UpdateAlerts200Response,

    /**
     * The UpdateAlerts200ResponseData model constructor.
     * @property {module:model/UpdateAlerts200ResponseData}
     */
    UpdateAlerts200ResponseData,

    /**
     * The UpdateApiKeys200Response model constructor.
     * @property {module:model/UpdateApiKeys200Response}
     */
    UpdateApiKeys200Response,

    /**
     * The UpdateApiKeys200ResponseData model constructor.
     * @property {module:model/UpdateApiKeys200ResponseData}
     */
    UpdateApiKeys200ResponseData,

    /**
     * The UpdateAssetPriceHistory200Response model constructor.
     * @property {module:model/UpdateAssetPriceHistory200Response}
     */
    UpdateAssetPriceHistory200Response,

    /**
     * The UpdateAssetPriceHistory200ResponseData model constructor.
     * @property {module:model/UpdateAssetPriceHistory200ResponseData}
     */
    UpdateAssetPriceHistory200ResponseData,

    /**
     * The UpdateAssets200Response model constructor.
     * @property {module:model/UpdateAssets200Response}
     */
    UpdateAssets200Response,

    /**
     * The UpdateAssets200ResponseData model constructor.
     * @property {module:model/UpdateAssets200ResponseData}
     */
    UpdateAssets200ResponseData,

    /**
     * The UpdateCompanies200Response model constructor.
     * @property {module:model/UpdateCompanies200Response}
     */
    UpdateCompanies200Response,

    /**
     * The UpdateCompanies200ResponseData model constructor.
     * @property {module:model/UpdateCompanies200ResponseData}
     */
    UpdateCompanies200ResponseData,

    /**
     * The UpdateConnections200Response model constructor.
     * @property {module:model/UpdateConnections200Response}
     */
    UpdateConnections200Response,

    /**
     * The UpdateConnections200ResponseData model constructor.
     * @property {module:model/UpdateConnections200ResponseData}
     */
    UpdateConnections200ResponseData,

    /**
     * The UpdateEndpoints200Response model constructor.
     * @property {module:model/UpdateEndpoints200Response}
     */
    UpdateEndpoints200Response,

    /**
     * The UpdateEndpoints200ResponseData model constructor.
     * @property {module:model/UpdateEndpoints200ResponseData}
     */
    UpdateEndpoints200ResponseData,

    /**
     * The UpdateFavorites200Response model constructor.
     * @property {module:model/UpdateFavorites200Response}
     */
    UpdateFavorites200Response,

    /**
     * The UpdateFavorites200ResponseData model constructor.
     * @property {module:model/UpdateFavorites200ResponseData}
     */
    UpdateFavorites200ResponseData,

    /**
     * The UpdatePostgenIntegrations200Response model constructor.
     * @property {module:model/UpdatePostgenIntegrations200Response}
     */
    UpdatePostgenIntegrations200Response,

    /**
     * The UpdatePostgenIntegrations200ResponseData model constructor.
     * @property {module:model/UpdatePostgenIntegrations200ResponseData}
     */
    UpdatePostgenIntegrations200ResponseData,

    /**
     * The UpdatePosts200Response model constructor.
     * @property {module:model/UpdatePosts200Response}
     */
    UpdatePosts200Response,

    /**
     * The UpdatePosts200ResponseData model constructor.
     * @property {module:model/UpdatePosts200ResponseData}
     */
    UpdatePosts200ResponseData,

    /**
     * The UpdateUsers200Response model constructor.
     * @property {module:model/UpdateUsers200Response}
     */
    UpdateUsers200Response,

    /**
     * The UpdateUsers200ResponseData model constructor.
     * @property {module:model/UpdateUsers200ResponseData}
     */
    UpdateUsers200ResponseData,

    /**
     * The Users model constructor.
     * @property {module:model/Users}
     */
    Users,

    /**
     * The UsersInput model constructor.
     * @property {module:model/UsersInput}
     */
    UsersInput,

    /**
     * The UsersUpdate model constructor.
     * @property {module:model/UsersUpdate}
     */
    UsersUpdate,

    /**
    * The APIKeysApi service constructor.
    * @property {module:api/APIKeysApi}
    */
    APIKeysApi,

    /**
    * The AlertsApi service constructor.
    * @property {module:api/AlertsApi}
    */
    AlertsApi,

    /**
    * The AssetPriceHistoryApi service constructor.
    * @property {module:api/AssetPriceHistoryApi}
    */
    AssetPriceHistoryApi,

    /**
    * The AssetUsecasesApi service constructor.
    * @property {module:api/AssetUsecasesApi}
    */
    AssetUsecasesApi,

    /**
    * The AssetsApi service constructor.
    * @property {module:api/AssetsApi}
    */
    AssetsApi,

    /**
    * The CloudProvidersApi service constructor.
    * @property {module:api/CloudProvidersApi}
    */
    CloudProvidersApi,

    /**
    * The CompaniesApi service constructor.
    * @property {module:api/CompaniesApi}
    */
    CompaniesApi,

    /**
    * The ConnectionsApi service constructor.
    * @property {module:api/ConnectionsApi}
    */
    ConnectionsApi,

    /**
    * The EndpointsApi service constructor.
    * @property {module:api/EndpointsApi}
    */
    EndpointsApi,

    /**
    * The FavoritesApi service constructor.
    * @property {module:api/FavoritesApi}
    */
    FavoritesApi,

    /**
    * The IndustriesApi service constructor.
    * @property {module:api/IndustriesApi}
    */
    IndustriesApi,

    /**
    * The JobFunctionsApi service constructor.
    * @property {module:api/JobFunctionsApi}
    */
    JobFunctionsApi,

    /**
    * The PostgenIntegrationsApi service constructor.
    * @property {module:api/PostgenIntegrationsApi}
    */
    PostgenIntegrationsApi,

    /**
    * The PostsApi service constructor.
    * @property {module:api/PostsApi}
    */
    PostsApi,

    /**
    * The StorageEnginesApi service constructor.
    * @property {module:api/StorageEnginesApi}
    */
    StorageEnginesApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
