/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Alert from './model/Alert';
import Apikey from './model/Apikey';
import Asset from './model/Asset';
import Assetpricehistory from './model/Assetpricehistory';
import Cloudprovider from './model/Cloudprovider';
import Company from './model/Company';
import Connection from './model/Connection';
import Error from './model/Error';
import Favorite from './model/Favorite';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineObject2 from './model/InlineObject2';
import InlineObject3 from './model/InlineObject3';
import User from './model/User';
import APIKeysApi from './api/APIKeysApi';
import AlertsApi from './api/AlertsApi';
import AssetPriceHistoryApi from './api/AssetPriceHistoryApi';
import AssetsApi from './api/AssetsApi';
import CloudProvidersApi from './api/CloudProvidersApi';
import CompaniesApi from './api/CompaniesApi';
import ConnectionsApi from './api/ConnectionsApi';
import FavoritesApi from './api/FavoritesApi';
import StorageEnginesApi from './api/StorageEnginesApi';
import UsersApi from './api/UsersApi';


/**
* Auto-generated API documentation for REST services of the Spartera platform.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SparteraApiDocumentation = require('index'); // See note below*.
* var xxxSvc = new SparteraApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SparteraApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SparteraApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SparteraApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Alert model constructor.
     * @property {module:model/Alert}
     */
    Alert,

    /**
     * The Apikey model constructor.
     * @property {module:model/Apikey}
     */
    Apikey,

    /**
     * The Asset model constructor.
     * @property {module:model/Asset}
     */
    Asset,

    /**
     * The Assetpricehistory model constructor.
     * @property {module:model/Assetpricehistory}
     */
    Assetpricehistory,

    /**
     * The Cloudprovider model constructor.
     * @property {module:model/Cloudprovider}
     */
    Cloudprovider,

    /**
     * The Company model constructor.
     * @property {module:model/Company}
     */
    Company,

    /**
     * The Connection model constructor.
     * @property {module:model/Connection}
     */
    Connection,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Favorite model constructor.
     * @property {module:model/Favorite}
     */
    Favorite,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject2 model constructor.
     * @property {module:model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:model/InlineObject3}
     */
    InlineObject3,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
    * The APIKeysApi service constructor.
    * @property {module:api/APIKeysApi}
    */
    APIKeysApi,

    /**
    * The AlertsApi service constructor.
    * @property {module:api/AlertsApi}
    */
    AlertsApi,

    /**
    * The AssetPriceHistoryApi service constructor.
    * @property {module:api/AssetPriceHistoryApi}
    */
    AssetPriceHistoryApi,

    /**
    * The AssetsApi service constructor.
    * @property {module:api/AssetsApi}
    */
    AssetsApi,

    /**
    * The CloudProvidersApi service constructor.
    * @property {module:api/CloudProvidersApi}
    */
    CloudProvidersApi,

    /**
    * The CompaniesApi service constructor.
    * @property {module:api/CompaniesApi}
    */
    CompaniesApi,

    /**
    * The ConnectionsApi service constructor.
    * @property {module:api/ConnectionsApi}
    */
    ConnectionsApi,

    /**
    * The FavoritesApi service constructor.
    * @property {module:api/FavoritesApi}
    */
    FavoritesApi,

    /**
    * The StorageEnginesApi service constructor.
    * @property {module:api/StorageEnginesApi}
    */
    StorageEnginesApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
