/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiSdk);
  }
}(this, function(expect, SparteraApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiSdk.AssetsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssetsApi', function() {
    describe('createAssets', function() {
      it('should call createAssets successfully', function(done) {
        //uncomment below and update the code to test createAssets
        //instance.createAssets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createAssetsAnalyze', function() {
      it('should call createAssetsAnalyze successfully', function(done) {
        //uncomment below and update the code to test createAssetsAnalyze
        //instance.createAssetsAnalyze(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createAssetsScanColumn', function() {
      it('should call createAssetsScanColumn successfully', function(done) {
        //uncomment below and update the code to test createAssetsScanColumn
        //instance.createAssetsScanColumn(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createAssetsTest', function() {
      it('should call createAssetsTest successfully', function(done) {
        //uncomment below and update the code to test createAssetsTest
        //instance.createAssetsTest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAssets', function() {
      it('should call deleteAssets successfully', function(done) {
        //uncomment below and update the code to test deleteAssets
        //instance.deleteAssets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetsById', function() {
      it('should call getAssetsById successfully', function(done) {
        //uncomment below and update the code to test getAssetsById
        //instance.getAssetsById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetsById2', function() {
      it('should call getAssetsById2 successfully', function(done) {
        //uncomment below and update the code to test getAssetsById2
        //instance.getAssetsById2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetsByIdAnalyze', function() {
      it('should call getAssetsByIdAnalyze successfully', function(done) {
        //uncomment below and update the code to test getAssetsByIdAnalyze
        //instance.getAssetsByIdAnalyze(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetsByIdInfoschema', function() {
      it('should call getAssetsByIdInfoschema successfully', function(done) {
        //uncomment below and update the code to test getAssetsByIdInfoschema
        //instance.getAssetsByIdInfoschema(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetsByIdInfoschemaSave', function() {
      it('should call getAssetsByIdInfoschemaSave successfully', function(done) {
        //uncomment below and update the code to test getAssetsByIdInfoschemaSave
        //instance.getAssetsByIdInfoschemaSave(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetsByIdPredictedPrice', function() {
      it('should call getAssetsByIdPredictedPrice successfully', function(done) {
        //uncomment below and update the code to test getAssetsByIdPredictedPrice
        //instance.getAssetsByIdPredictedPrice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetsByIdStatistics', function() {
      it('should call getAssetsByIdStatistics successfully', function(done) {
        //uncomment below and update the code to test getAssetsByIdStatistics
        //instance.getAssetsByIdStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAssetsByIdTest', function() {
      it('should call getAssetsByIdTest successfully', function(done) {
        //uncomment below and update the code to test getAssetsByIdTest
        //instance.getAssetsByIdTest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAssets', function() {
      it('should call listAssets successfully', function(done) {
        //uncomment below and update the code to test listAssets
        //instance.listAssets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAssetsSearch', function() {
      it('should call listAssetsSearch successfully', function(done) {
        //uncomment below and update the code to test listAssetsSearch
        //instance.listAssetsSearch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAssets', function() {
      it('should call updateAssets successfully', function(done) {
        //uncomment below and update the code to test updateAssets
        //instance.updateAssets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
