/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiDocumentation);
  }
}(this, function(expect, SparteraApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiDocumentation.CompaniesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompaniesApi', function() {
    describe('companiesCompanyIdAnalyticsAssetsGet', function() {
      it('should call companiesCompanyIdAnalyticsAssetsGet successfully', function(done) {
        //uncomment below and update the code to test companiesCompanyIdAnalyticsAssetsGet
        //instance.companiesCompanyIdAnalyticsAssetsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesCompanyIdAnalyticsCustomersGet', function() {
      it('should call companiesCompanyIdAnalyticsCustomersGet successfully', function(done) {
        //uncomment below and update the code to test companiesCompanyIdAnalyticsCustomersGet
        //instance.companiesCompanyIdAnalyticsCustomersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesCompanyIdAnalyticsDashboardGet', function() {
      it('should call companiesCompanyIdAnalyticsDashboardGet successfully', function(done) {
        //uncomment below and update the code to test companiesCompanyIdAnalyticsDashboardGet
        //instance.companiesCompanyIdAnalyticsDashboardGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesCompanyIdAnalyticsSalesGet', function() {
      it('should call companiesCompanyIdAnalyticsSalesGet successfully', function(done) {
        //uncomment below and update the code to test companiesCompanyIdAnalyticsSalesGet
        //instance.companiesCompanyIdAnalyticsSalesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesCompanyIdGet', function() {
      it('should call companiesCompanyIdGet successfully', function(done) {
        //uncomment below and update the code to test companiesCompanyIdGet
        //instance.companiesCompanyIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesCompanyIdObjectsGet', function() {
      it('should call companiesCompanyIdObjectsGet successfully', function(done) {
        //uncomment below and update the code to test companiesCompanyIdObjectsGet
        //instance.companiesCompanyIdObjectsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesCompanyIdPatch', function() {
      it('should call companiesCompanyIdPatch successfully', function(done) {
        //uncomment below and update the code to test companiesCompanyIdPatch
        //instance.companiesCompanyIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesCompanyIdRequestsPlanGet', function() {
      it('should call companiesCompanyIdRequestsPlanGet successfully', function(done) {
        //uncomment below and update the code to test companiesCompanyIdRequestsPlanGet
        //instance.companiesCompanyIdRequestsPlanGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('companiesCompanyIdRequestsUsageGet', function() {
      it('should call companiesCompanyIdRequestsUsageGet successfully', function(done) {
        //uncomment below and update the code to test companiesCompanyIdRequestsUsageGet
        //instance.companiesCompanyIdRequestsUsageGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
