/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiSdk);
  }
}(this, function(expect, SparteraApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiSdk.CompaniesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompaniesApi', function() {
    describe('getCompaniesById', function() {
      it('should call getCompaniesById successfully', function(done) {
        //uncomment below and update the code to test getCompaniesById
        //instance.getCompaniesById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCompanies', function() {
      it('should call listCompanies successfully', function(done) {
        //uncomment below and update the code to test listCompanies
        //instance.listCompanies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCompaniesAnalyticsAssets', function() {
      it('should call listCompaniesAnalyticsAssets successfully', function(done) {
        //uncomment below and update the code to test listCompaniesAnalyticsAssets
        //instance.listCompaniesAnalyticsAssets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCompaniesAnalyticsCustomers', function() {
      it('should call listCompaniesAnalyticsCustomers successfully', function(done) {
        //uncomment below and update the code to test listCompaniesAnalyticsCustomers
        //instance.listCompaniesAnalyticsCustomers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCompaniesAnalyticsDashboard', function() {
      it('should call listCompaniesAnalyticsDashboard successfully', function(done) {
        //uncomment below and update the code to test listCompaniesAnalyticsDashboard
        //instance.listCompaniesAnalyticsDashboard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCompaniesAnalyticsMetrics', function() {
      it('should call listCompaniesAnalyticsMetrics successfully', function(done) {
        //uncomment below and update the code to test listCompaniesAnalyticsMetrics
        //instance.listCompaniesAnalyticsMetrics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCompaniesAnalyticsSales', function() {
      it('should call listCompaniesAnalyticsSales successfully', function(done) {
        //uncomment below and update the code to test listCompaniesAnalyticsSales
        //instance.listCompaniesAnalyticsSales(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCompaniesObjects', function() {
      it('should call listCompaniesObjects successfully', function(done) {
        //uncomment below and update the code to test listCompaniesObjects
        //instance.listCompaniesObjects(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCompaniesRequestsUsage', function() {
      it('should call listCompaniesRequestsUsage successfully', function(done) {
        //uncomment below and update the code to test listCompaniesRequestsUsage
        //instance.listCompaniesRequestsUsage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCompanies', function() {
      it('should call updateCompanies successfully', function(done) {
        //uncomment below and update the code to test updateCompanies
        //instance.updateCompanies(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
