/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiSdk);
  }
}(this, function(expect, SparteraApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiSdk.EndpointsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EndpointsApi', function() {
    describe('createEndpoints', function() {
      it('should call createEndpoints successfully', function(done) {
        //uncomment below and update the code to test createEndpoints
        //instance.createEndpoints(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createEndpointsKeys', function() {
      it('should call createEndpointsKeys successfully', function(done) {
        //uncomment below and update the code to test createEndpointsKeys
        //instance.createEndpointsKeys(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEndpoints', function() {
      it('should call deleteEndpoints successfully', function(done) {
        //uncomment below and update the code to test deleteEndpoints
        //instance.deleteEndpoints(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEndpointsKeys', function() {
      it('should call deleteEndpointsKeys successfully', function(done) {
        //uncomment below and update the code to test deleteEndpointsKeys
        //instance.deleteEndpointsKeys(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEndpointsById', function() {
      it('should call getEndpointsById successfully', function(done) {
        //uncomment below and update the code to test getEndpointsById
        //instance.getEndpointsById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEndpointsByIdAvailableEndpoints', function() {
      it('should call getEndpointsByIdAvailableEndpoints successfully', function(done) {
        //uncomment below and update the code to test getEndpointsByIdAvailableEndpoints
        //instance.getEndpointsByIdAvailableEndpoints(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEndpointsByIdConnectionsDescribe', function() {
      it('should call getEndpointsByIdConnectionsDescribe successfully', function(done) {
        //uncomment below and update the code to test getEndpointsByIdConnectionsDescribe
        //instance.getEndpointsByIdConnectionsDescribe(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEndpointsByIdExecute', function() {
      it('should call getEndpointsByIdExecute successfully', function(done) {
        //uncomment below and update the code to test getEndpointsByIdExecute
        //instance.getEndpointsByIdExecute(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEndpointsByIdKeys', function() {
      it('should call getEndpointsByIdKeys successfully', function(done) {
        //uncomment below and update the code to test getEndpointsByIdKeys
        //instance.getEndpointsByIdKeys(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEndpointsByIdStats', function() {
      it('should call getEndpointsByIdStats successfully', function(done) {
        //uncomment below and update the code to test getEndpointsByIdStats
        //instance.getEndpointsByIdStats(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEndpointsByIdTest', function() {
      it('should call getEndpointsByIdTest successfully', function(done) {
        //uncomment below and update the code to test getEndpointsByIdTest
        //instance.getEndpointsByIdTest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEndpointsByIdUrl', function() {
      it('should call getEndpointsByIdUrl successfully', function(done) {
        //uncomment below and update the code to test getEndpointsByIdUrl
        //instance.getEndpointsByIdUrl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listEndpoints', function() {
      it('should call listEndpoints successfully', function(done) {
        //uncomment below and update the code to test listEndpoints
        //instance.listEndpoints(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateEndpoints', function() {
      it('should call updateEndpoints successfully', function(done) {
        //uncomment below and update the code to test updateEndpoints
        //instance.updateEndpoints(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
