/**
 * Spartera API Documentation
 * Auto-generated API documentation for REST services of the Spartera platform
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: support@spartera.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SparteraApiSdk);
  }
}(this, function(expect, SparteraApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SparteraApiSdk.FavoritesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FavoritesApi', function() {
    describe('createFavorites', function() {
      it('should call createFavorites successfully', function(done) {
        //uncomment below and update the code to test createFavorites
        //instance.createFavorites(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFavorites', function() {
      it('should call deleteFavorites successfully', function(done) {
        //uncomment below and update the code to test deleteFavorites
        //instance.deleteFavorites(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoritesById', function() {
      it('should call getFavoritesById successfully', function(done) {
        //uncomment below and update the code to test getFavoritesById
        //instance.getFavoritesById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoritesByIdUsers', function() {
      it('should call getFavoritesByIdUsers successfully', function(done) {
        //uncomment below and update the code to test getFavoritesByIdUsers
        //instance.getFavoritesByIdUsers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoritesByIdUsersCategory', function() {
      it('should call getFavoritesByIdUsersCategory successfully', function(done) {
        //uncomment below and update the code to test getFavoritesByIdUsersCategory
        //instance.getFavoritesByIdUsersCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoritesByIdUsersCheck', function() {
      it('should call getFavoritesByIdUsersCheck successfully', function(done) {
        //uncomment below and update the code to test getFavoritesByIdUsersCheck
        //instance.getFavoritesByIdUsersCheck(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoritesByIdUsersUncategorized', function() {
      it('should call getFavoritesByIdUsersUncategorized successfully', function(done) {
        //uncomment below and update the code to test getFavoritesByIdUsersUncategorized
        //instance.getFavoritesByIdUsersUncategorized(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateFavorites', function() {
      it('should call updateFavorites successfully', function(done) {
        //uncomment below and update the code to test updateFavorites
        //instance.updateFavorites(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
